/**
 * Game Mechanics Constants
 * Single source of truth for all numeric values that control game rules.
 * Import from here instead of hardcoding magic numbers across the codebase.
 */

// ============================================================================
// CHARACTER — STAT DERIVATION MULTIPLIERS
// ============================================================================
// Applied to each base stat (body / mind / heart) to produce the four
// derived combat stats for that attribute category.

export const STAT_MULTIPLIERS = {
    ATTACK:  1,   // physicalAttack / mentalAttack / emotionalAttack — combat rolls
    SKILL:   1,   // physicalSkill / mentalSkill / emotionalSkill — skill usage, philosophy bar
    DEFENSE: 3,
    SAVE:    2,
    TEST:    4,
} as const;

// ============================================================================
// CHARACTER — RESOURCE CALCULATIONS
// ============================================================================
// Scaling factor applied to the base-stat sum when computing max health.
// Formula: maxHealth = (body + heart + mind) × HEALTH_PER_STAT.
// Level influences health through the authored stat budget, not by a second
// multiplicative level factor.

export const RESOURCE_MULTIPLIERS = {
    HEALTH_PER_STAT: 5,
} as const;

// ============================================================================
// PROGRESSION — EXPERIENCE & LEVELING
// ============================================================================

export const EXPERIENCE_PER_LEVEL = 1000;

// Stat points granted per level promotion (Spec 06 Q3). Spent via
// `allocateStatPoint` to raise heart / body / mind. Per Spec 06 Q5 there is
// no level cap today, so the points stream is uncapped — content authors
// decide where progression naturally stops.
export const STAT_POINTS_PER_LEVEL = 3;

// ============================================================================
// COMBAT — DEFENSE MULTIPLIERS
// ============================================================================
// Applied to a combatant's base defense stat when they choose the 'defend'
// action.  The multiplier is selected based on the defender's type-advantage
// relative to the attacker (heart > body > mind > heart).
//
//   Defending with ADVANTAGE    → 3× defense  (picked the right counter-type)
//   Defending with NEUTRAL      → 2× defense  (same type, no bonus)
//   Defending with DISADVANTAGE → 1.5× defense (picked the wrong type, weaker)
//
// Keys deliberately match the Advantage union type so they can be used as
// a direct lookup: DEFENSE_MULTIPLIERS[advantage].

export const DEFENSE_MULTIPLIERS: Record<'advantage' | 'neutral' | 'disadvantage', number> = {
    advantage:    2,
    neutral:      1.5,
    disadvantage: 1.0,
} as const;

// Applied when a combatant did NOT choose the 'defend' action (i.e. they are
// taking damage after losing an attack contest with no active defense bonus).
export const PASSIVE_DEFENSE_MULTIPLIER = 1;

// ============================================================================
// EFFECTS — STACKING CAPS
// ============================================================================
// Hard ceiling on how high any single effect's intensity or remaining duration
// can grow, regardless of stacking mode or repeated applications.

export const MAX_EFFECT_INTENSITY = 10;
export const MAX_EFFECT_DURATION  = 10;

// ============================================================================
// SKILLS — SCALING & RESOURCE GENERATION
// ============================================================================
// Per Spec 04, skills use a five-resource resonance economy. Basic actions
// generate tokens of the actor's stance colour; the multiplier below feeds
// into skill damage scaling off the skill's `scalingStat`.
//
//   damage = skill.basePower
//          + character.baseStats[skill.scalingStat] × SKILL_STAT_MULTIPLIER

export const SKILL_STAT_MULTIPLIER = 0.5;

/** Tokens generated by basic actions, keyed by outcome. */
export const RESOURCE_GENERATION = {
    ATTACK_HIT:  3,
    ATTACK_MISS: 1,
    DEFEND:      5,
} as const;

// ============================================================================
// COMBAT — FRIENDSHIP MECHANIC
// ============================================================================
// When both combatants choose 'defend' on the same turn the friendship
// counter increments.  Reaching the maximum ends combat peacefully.

export const FRIENDSHIP_COUNTER_MAX = 3;

// Phase 150 — probability that an enemy answers a player's HOSTILE skill with
// a skill of its own ("answer power with power"). Distinct from the Phase 49
// lead-with-skill cadence (`ENEMY_SKILL_PICK_CHANCE`): this dial governs the
// REACTIVE answer to the player's offensive skill, not the enemy's own opening.
// Set at 0.10 — a felt but not overwhelming reactive threat. A guaranteed
// (1.0) answer crushes both the STRATEGIST friendship route and the difficult
// lethal anchor (`balance-judge`); an answer-chance sweep on the Phase 121
// difficult anchor found win rate 0.04 at 0.20–0.35, 0.12 at 0.15, and 0.16 at
// 0.10 against an authored band of 0.10–0.40, while the normal anchor (0.80)
// and difficult-anchor friendship rate (0.20) stay flat across the range. 0.10
// keeps the doctrine ("answer power with power") alive with safe band margin;
// it is a deliberate floor, flagged as a tuning candidate to raise once the
// difficult anchor's stat block is retuned. Recorded in
// automation/playtest/BALANCE_LEDGER.md (marker M-150).
export const ENEMY_SKILL_ANSWER_CHANCE = 0.10;

// Phase 125 — Effects-driven resolution thresholds
// Combined intensity of control/debuff effects needed to force saturation yield (friendship route)
export const EFFECTS_RESOLUTION_DEBUFF_INTENSITY_THRESHOLD = 3;
// Minimum DoT damage per round needed to force erosion victory route
export const EFFECTS_RESOLUTION_DOT_DAMAGE_THRESHOLD = 2;
// Horizon (in rounds) for the DoT-erosion victory route: DoT forces an early
// victory only if it could finish the enemy within this many rounds. This is
// the conservative gate that decides whether sustained status damage "clearly
// closes the fight" — NOT the combat timeout (that is the ~80-round cap in the
// playtest/combat loop). On high-HP enemies the default 10 is unreachable
// (rounds-to-kill scales with HP), which is why lowering the damage threshold
// alone never resolved L30+ timeouts; raising this horizon lets a strong DoT
// resolve a fight it will demonstrably win before the cap. Tuned by the loop.
export const EFFECTS_RESOLUTION_DOT_MAX_ROUNDS_TO_KILL = 10;

// Base intensity granted per proc-applied status effect when the trigger does
// not override it. Control effects stack by DURATION (their intensity stays at
// this base), so the saturation-yield route's combined-intensity threshold is
// only reachable when several control effects are active OR this base is raised.
// Symmetric (applies to whoever procs the effect), so the defeat-regression
// guard bounds it; engagement-positive (more decisive status). Tuned by the loop.
export const EFFECT_BASE_PROC_INTENSITY = 2; // Phase 130 — raised from 1 for l15 STRATEGIST targeting

// Phase 157 — Status-centered affix draw bias.
// The affix library (`src/Items/affix.library.ts`) is content-rich with status-
// applying prefixes/suffixes (poison/burn/bleed/stun/fear/curse/sleep/…), but
// most of them sit at `uncommon_mod`/`rare_mod` draw weight (3/1) while the
// flat-stat affixes (Keen/Crushing/Fortified/…) are `common_mod` (10). Left
// unbiased, a weighted affix draw is dominated by boring flat-stat trading and
// the rich status content is mathematically suppressed — a direct violation of
// the load-bearing doctrine ("status effects are the MAIN fun").
//
// This multiplier is applied to the draw weight of OFFENSIVE status-applying
// affixes (status-tagged, on a status-applying slot, not pure defensive/sustain)
// so a roll meaningfully *feeds status-effect play* without erasing flat-stat
// variety entirely. At the default `3`, an uncommon status affix (3×3=9) is
// competitive with a common flat-stat affix (10) and a rare status affix (1×3=3)
// matches an uncommon flat-stat one. Engagement-positive; tuned by the loop.
export const STATUS_AFFIX_DRAW_BIAS = 3;

// ============================================================================
// ENEMY — STAT BUDGET PER LEVEL
// ============================================================================
// Total base-stat budget granted to an enemy is `level × ENEMY_STAT_PER_LEVEL`,
// distributed across heart / body / mind. Players, by contrast, carry a
// `level × 5` budget, so the default `3` makes a same-level enemy roughly 60%
// of a player's raw stat weight — a starting point the tuning workflow A/B's.
//
// This is the single tunable knob for global enemy power scaling. Authored
// enemies that opt into budget-based stats build their `baseStats` via
// `enemyStatBudget(level)` (see `src/Enemy/index.ts`); legacy enemies that
// hand-author `baseStats` are unaffected.
export const ENEMY_STAT_PER_LEVEL = 3;

// Off-budget "gear tier" scaling term to counteract player power accumulation.
// Represents the compounding advantage players gain from equipment upgrades and
// skill library expansion that enemies lack. Applied as a multiplicative bonus
// to enemy defensive stats (HP/defense/resists), weighted away from attack to
// avoid defeat spikes. The curve is ≈0 at level 1 (early game untouched) and
// grows with level to balance late-game trivialization. Magnitude is tuned by
// the mechanics loop via the tunable registry.
export const ENEMY_GEAR_TIER_PER_LEVEL = 0.02;
