/**
 * Game Mechanics Constants
 * Single source of truth for all numeric values that control game rules.
 * Import from here instead of hardcoding magic numbers across the codebase.
 */

// ============================================================================
// CHARACTER — STAT DERIVATION MULTIPLIERS
// ============================================================================
// Applied to each base stat (body / mind / heart) to produce the four
// derived combat stats for that attribute category.

export const STAT_MULTIPLIERS = {
    ATTACK:  1,   // physicalAttack / mentalAttack / emotionalAttack — combat rolls
    SKILL:   1,   // physicalSkill / mentalSkill / emotionalSkill — skill usage, philosophy bar
    DEFENSE: 3,
    SAVE:    2,
    TEST:    4,
} as const;

// ============================================================================
// CHARACTER — RESOURCE CALCULATIONS
// ============================================================================
// Scaling factor applied to the base-stat sum when computing max health.
// Formula: maxHealth = (body + heart + mind) × HEALTH_PER_STAT.
// Level influences health through the authored stat budget, not by a second
// multiplicative level factor.

export const RESOURCE_MULTIPLIERS = {
    HEALTH_PER_STAT: 5,
} as const;

// ============================================================================
// PROGRESSION — EXPERIENCE & LEVELING
// ============================================================================

export const EXPERIENCE_PER_LEVEL = 1000;

// Stat points granted per level promotion (Spec 06 Q3). Spent via
// `allocateStatPoint` to raise heart / body / mind. Per Spec 06 Q5 there is
// no level cap today, so the points stream is uncapped — content authors
// decide where progression naturally stops.
export const STAT_POINTS_PER_LEVEL = 3;

// ============================================================================
// COMBAT — DEFENSE MULTIPLIERS
// ============================================================================
// Applied to a combatant's base defense stat when they choose the 'defend'
// action.  The multiplier is selected based on the defender's type-advantage
// relative to the attacker (heart > body > mind > heart).
//
//   Defending with ADVANTAGE    → 3× defense  (picked the right counter-type)
//   Defending with NEUTRAL      → 2× defense  (same type, no bonus)
//   Defending with DISADVANTAGE → 1.5× defense (picked the wrong type, weaker)
//
// Keys deliberately match the Advantage union type so they can be used as
// a direct lookup: DEFENSE_MULTIPLIERS[advantage].

export const DEFENSE_MULTIPLIERS: Record<'advantage' | 'neutral' | 'disadvantage', number> = {
    advantage:    2,
    neutral:      1.5,
    disadvantage: 1.0,
} as const;

// Applied when a combatant did NOT choose the 'defend' action (i.e. they are
// taking damage after losing an attack contest with no active defense bonus).
export const PASSIVE_DEFENSE_MULTIPLIER = 1;

// ============================================================================
// EFFECTS — STACKING CAPS
// ============================================================================
// Hard ceiling on how high any single effect's intensity or remaining duration
// can grow, regardless of stacking mode or repeated applications.

export const MAX_EFFECT_INTENSITY = 10;
export const MAX_EFFECT_DURATION  = 10;

// ============================================================================
// SKILLS — SCALING & RESOURCE GENERATION
// ============================================================================
// Per Spec 04, skills use a five-resource resonance economy. Basic actions
// generate tokens of the actor's stance colour; the multiplier below feeds
// into skill damage scaling off the skill's `scalingStat`.
//
//   damage = skill.basePower
//          + character.baseStats[skill.scalingStat] × SKILL_STAT_MULTIPLIER

export const SKILL_STAT_MULTIPLIER = 0.5;

/** Tokens generated by basic actions, keyed by outcome. */
export const RESOURCE_GENERATION = {
    ATTACK_HIT:  3,
    ATTACK_MISS: 1,
    DEFEND:      5,
} as const;

// ============================================================================
// COMBAT — FRIENDSHIP MECHANIC
// ============================================================================
// When both combatants choose 'defend' on the same turn the friendship
// counter increments.  Reaching the maximum ends combat peacefully.

export const FRIENDSHIP_COUNTER_MAX = 3;

// Phase 125 — Effects-driven resolution thresholds
// Combined intensity of control/debuff effects needed to force saturation yield (friendship route)
export const EFFECTS_RESOLUTION_DEBUFF_INTENSITY_THRESHOLD = 6;
// Minimum DoT damage per round needed to force erosion victory route  
export const EFFECTS_RESOLUTION_DOT_DAMAGE_THRESHOLD = 5;

// ============================================================================
// ENEMY — STAT BUDGET PER LEVEL
// ============================================================================
// Total base-stat budget granted to an enemy is `level × ENEMY_STAT_PER_LEVEL`,
// distributed across heart / body / mind. Players, by contrast, carry a
// `level × 5` budget, so the default `3` makes a same-level enemy roughly 60%
// of a player's raw stat weight — a starting point the tuning workflow A/B's.
//
// This is the single tunable knob for global enemy power scaling. Authored
// enemies that opt into budget-based stats build their `baseStats` via
// `enemyStatBudget(level)` (see `src/Enemy/index.ts`); legacy enemies that
// hand-author `baseStats` are unaffected.
export const ENEMY_STAT_PER_LEVEL = 3;

// Off-budget "gear tier" scaling term to counteract player power accumulation.
// Represents the compounding advantage players gain from equipment upgrades and
// skill library expansion that enemies lack. Applied as a multiplicative bonus
// to enemy defensive stats (HP/defense/resists), weighted away from attack to
// avoid defeat spikes. The curve is ≈0 at level 1 (early game untouched) and
// grows with level to balance late-game trivialization. Magnitude is tuned by
// the mechanics loop via the tunable registry.
export const ENEMY_GEAR_TIER_PER_LEVEL = 0.02;
