import type { Config } from 'jest';

const config: Config = {
    preset: 'ts-jest',
    testEnvironment: 'node',
    roots: ['<rootDir>/src'],
    testMatch: ['**/*.test.ts'],
    moduleNameMapper: {
        '^Character/(.*)$': '<rootDir>/src/Character/$1',
        '^Character$': '<rootDir>/src/Character/index',
        '^Combat/(.*)$': '<rootDir>/src/Combat/$1',
        '^Combat$': '<rootDir>/src/Combat/index',
        '^Enemy/(.*)$': '<rootDir>/src/Enemy/$1',
        '^Enemy$': '<rootDir>/src/Enemy/index',
        '^Effects/(.*)$': '<rootDir>/src/Effects/$1',
        '^Effects$': '<rootDir>/src/Effects/index',
        '^Items/(.*)$': '<rootDir>/src/Items/$1',
        '^Items$': '<rootDir>/src/Items/index',
        '^Skills/(.*)$': '<rootDir>/src/Skills/$1',
        '^Skills$': '<rootDir>/src/Skills/index',
        '^Utils/(.*)$': '<rootDir>/src/Utils/$1',
        '^Utils$': '<rootDir>/src/Utils/index',
        '^World/(.*)$': '<rootDir>/src/World/$1',
        '^World$': '<rootDir>/src/World/index',
        '^Game/(.*)$': '<rootDir>/src/Game/$1',
        '^Game$': '<rootDir>/src/Game/index',
        '^NPCs/(.*)$': '<rootDir>/src/NPCs/$1',
        '^NPCs$': '<rootDir>/src/NPCs/index',
        '^@Character/(.*)$': '<rootDir>/src/Character/$1',
        '^@Combat/(.*)$': '<rootDir>/src/Combat/$1',
        '^@Enemy/(.*)$': '<rootDir>/src/Enemy/$1',
        '^@Effects/(.*)$': '<rootDir>/src/Effects/$1',
        '^@Items/(.*)$': '<rootDir>/src/Items/$1',
        '^@Skills/(.*)$': '<rootDir>/src/Skills/$1',
        '^@Utils/(.*)$': '<rootDir>/src/Utils/$1',
        '^@World/(.*)$': '<rootDir>/src/World/$1',
        '^@Game/(.*)$': '<rootDir>/src/Game/$1',
        '^@NPCs/(.*)$': '<rootDir>/src/NPCs/$1',
    },
    collectCoverageFrom: [
        'src/**/*.ts',
        '!src/**/*.d.ts',
        '!src/**/*.cli.ts',
        '!src/**/*.mock.ts',
        '!src/CLI/**',
    ],
};

export default config;
