/**
 * Affix Library — prefix/suffix naming layer (2026-06-07 content pass).
 *
 * A thin, data-only naming layer that sits *on top of* the Spec 05d rolled-
 * modifier engine. Each `Affix` (see `modifier.types.ts`) couples a flavourful
 * display `word` to one or more existing catalogue modifier IDs via `modIds`.
 *
 * The drop factory (`dropItemWithAffixes` in `item.factory.ts`) selects affixes
 * appropriate to an item's slot + level, folds their `modIds` into the rolled
 * modifier set, and decorates the item's name via `composeItemName`:
 *   - prefix  → "<word> <base>"            e.g. "Keen Iron Blade"
 *   - suffix  → "<base> <word>"            e.g. "Iron Blade of the Bear"
 *   - both    → "<prefix> <base> <suffix>" e.g. "Keen Iron Blade of the Bear"
 *
 * Invariants kept here on purpose (mirrors the catalogue conventions):
 *   - `modIds` reference EXISTING catalogue modifiers only (procedural or
 *     unique). The factory resolves them through the same `getModifierById` /
 *     `pickValueTier` machinery a normal rolled mod uses.
 *   - `validSlots` must be compatible with every referenced mod's own
 *     `validSlots` (an affix is never offered on a slot its mods can't roll on).
 *   - `hiddenRarity` reuses the `HiddenModRarity` weights so affix selection
 *     shares the catalogue's common/uncommon/rare draw distribution.
 *
 * This layer is purely additive — `dropItem` is untouched; callers opt in via
 * `dropItemWithAffixes`.
 */

import { EquipmentSlot } from './types';
import { Affix, AffixRole, HiddenModRarity } from './modifier.types';

// ─── Prefixes (lead the item name) ───────────────────────────────────────────

export const prefixes: Affix[] = [
    {
        id: 'pfx-keen',
        word: 'Keen',
        role: 'prefix',
        modIds: ['wm-flat-damage'],
        validSlots: ['weapon'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-07',
        tags: ['affix', 'prefix', 'weapon', 'offense'],
    },
    {
        id: 'pfx-honed',
        word: 'Honed',
        role: 'prefix',
        modIds: ['wm-skill-edge'],
        validSlots: ['weapon'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-07',
        tags: ['affix', 'prefix', 'weapon', 'offense'],
    },
    {
        id: 'pfx-vicious',
        word: 'Vicious',
        role: 'prefix',
        modIds: ['wm-flat-damage', 'wm-crit-rate'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-07',
        tags: ['affix', 'prefix', 'weapon', 'offense', 'crit'],
    },
    {
        id: 'pfx-savage',
        word: 'Savage',
        role: 'prefix',
        modIds: ['wm-crit-damage'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 20,
        addedIn: '2026-06-07',
        tags: ['affix', 'prefix', 'weapon', 'offense', 'crit'],
    },
    {
        id: 'pfx-vampiric',
        word: 'Vampiric',
        role: 'prefix',
        modIds: ['wm-lifesteal'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 1,
        addedIn: '2026-06-07',
        tags: ['affix', 'prefix', 'weapon', 'sustain'],
    },
    {
        id: 'pfx-crushing',
        word: 'Crushing',
        role: 'prefix',
        modIds: ['hndm-strength'],
        validSlots: ['hands'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-07',
        tags: ['affix', 'prefix', 'hands', 'offense'],
    },
    {
        id: 'pfx-fortified',
        word: 'Fortified',
        role: 'prefix',
        modIds: ['bm-armor'],
        validSlots: ['body'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-07',
        tags: ['affix', 'prefix', 'body', 'defense'],
    },
    {
        id: 'pfx-hardened',
        word: 'Hardened',
        role: 'prefix',
        modIds: ['armm-defense'],
        validSlots: ['armor'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-07',
        tags: ['affix', 'prefix', 'armor', 'defense'],
    },
    {
        id: 'pfx-stalwart',
        word: 'Stalwart',
        role: 'prefix',
        modIds: ['bm-vitality'],
        validSlots: ['body'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-07',
        tags: ['affix', 'prefix', 'body', 'defense'],
    },
    {
        id: 'pfx-swift',
        word: 'Swift',
        role: 'prefix',
        modIds: ['fm-evasion'],
        validSlots: ['feet'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-07',
        tags: ['affix', 'prefix', 'feet', 'evasion'],
    },
    {
        id: 'pfx-phantom',
        word: 'Phantom',
        role: 'prefix',
        modIds: ['fm-evasion-proc'],
        validSlots: ['feet'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-07',
        tags: ['affix', 'prefix', 'feet', 'evasion'],
    },
    {
        id: 'pfx-warded',
        word: 'Warded',
        role: 'prefix',
        modIds: ['hm-mental-defense'],
        validSlots: ['head'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-07',
        tags: ['affix', 'prefix', 'head', 'defense', 'mental'],
    },
    {
        id: 'pfx-sage',
        word: 'Sage',
        role: 'prefix',
        modIds: ['hm-insight'],
        validSlots: ['head'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 5,
        addedIn: '2026-06-07',
        tags: ['affix', 'prefix', 'head', 'mental'],
    },
    {
        id: 'pfx-balanced',
        word: 'Balanced',
        role: 'prefix',
        modIds: ['am-cross-stat'],
        validSlots: ['accessory'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-07',
        tags: ['affix', 'prefix', 'accessory', 'utility'],
    },
    {
        id: 'pfx-resonant',
        word: 'Resonant',
        role: 'prefix',
        modIds: ['am-stance-res'],
        validSlots: ['accessory'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 1,
        addedIn: '2026-06-07',
        tags: ['affix', 'prefix', 'accessory', 'resource'],
    },
    {
        id: 'pfx-blazing',
        word: 'Blazing',
        role: 'prefix',
        modIds: ['wm-bleeding-edge'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-07',
        tags: ['affix', 'prefix', 'weapon', 'dot'],
    },
    // ─── Phase 151 expansion (2026-06-16): 20 new prefixes ───────────────────
    // Status-effect prefixes (weapon)
    {
        id: 'pfx-venomous',
        word: 'Venomous',
        role: 'prefix',
        modIds: ['wm-venom-coat'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'weapon', 'status', 'dot'],
    },
    {
        id: 'pfx-frostbitten',
        word: 'Frostbitten',
        role: 'prefix',
        modIds: ['wm-frost-brand'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'weapon', 'status', 'control'],
    },
    {
        id: 'pfx-storming',
        word: 'Storming',
        role: 'prefix',
        modIds: ['wm-storm-edge'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 15,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'weapon', 'status', 'control'],
    },
    {
        id: 'pfx-stunning',
        word: 'Stunning',
        role: 'prefix',
        modIds: ['wm-dazing-pommel'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 5,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'weapon', 'status', 'control'],
    },
    {
        id: 'pfx-baleful',
        word: 'Baleful',
        role: 'prefix',
        modIds: ['wm-status-amp'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 10,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'weapon', 'status'],
    },
    // Card / resource prefixes
    {
        id: 'pfx-channeling',
        word: 'Channeling',
        role: 'prefix',
        modIds: ['wm-mind-gen'],
        validSlots: ['weapon'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'weapon', 'resource'],
    },
    {
        id: 'pfx-calculating',
        word: 'Calculating',
        role: 'prefix',
        modIds: ['hndm-mind-gen'],
        validSlots: ['hands'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'hands', 'resource'],
    },
    {
        id: 'pfx-resolved',
        word: 'Resolved',
        role: 'prefix',
        modIds: ['bm-heart-start'],
        validSlots: ['body'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'body', 'resource'],
    },
    {
        id: 'pfx-vanguard',
        word: 'Vanguard',
        role: 'prefix',
        modIds: ['fm-initiative-tokens'],
        validSlots: ['feet'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'feet', 'resource', 'initiative'],
    },
    // Mobility / initiative prefixes
    {
        id: 'pfx-shadowed',
        word: 'Shadowed',
        role: 'prefix',
        modIds: ['fm-stealth'],
        validSlots: ['feet'],
        hiddenRarity: 'rare_mod',
        minLevel: 10,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'feet', 'utility', 'evasion'],
    },
    {
        id: 'pfx-lucky',
        word: 'Lucky',
        role: 'prefix',
        modIds: ['fm-luck'],
        validSlots: ['feet'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'feet', 'utility', 'luck'],
    },
    // Defensive prefixes
    {
        id: 'pfx-provoking',
        word: 'Provoking',
        role: 'prefix',
        modIds: ['bm-taunt-proc'],
        validSlots: ['body'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 5,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'body', 'defense', 'control'],
    },
    {
        id: 'pfx-warding',
        word: 'Warding',
        role: 'prefix',
        modIds: ['bm-barrier-proc'],
        validSlots: ['body'],
        hiddenRarity: 'rare_mod',
        minLevel: 10,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'body', 'defense', 'proc'],
    },
    {
        id: 'pfx-adamant',
        word: 'Adamant',
        role: 'prefix',
        modIds: ['armm-body-resist'],
        validSlots: ['armor'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'armor', 'defense'],
    },
    {
        id: 'pfx-sanguine',
        word: 'Sanguine',
        role: 'prefix',
        modIds: ['armm-heart-resist'],
        validSlots: ['armor'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'armor', 'defense', 'emotional'],
    },
    {
        id: 'pfx-reinforced',
        word: 'Reinforced',
        role: 'prefix',
        modIds: ['armm-mhp'],
        validSlots: ['armor'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 5,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'armor', 'defense'],
    },
    {
        id: 'pfx-stoic',
        word: 'Stoic',
        role: 'prefix',
        modIds: ['hm-mind-resist'],
        validSlots: ['head'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'head', 'defense', 'mental'],
    },
    // Aggressive / disruptive prefixes (hands)
    {
        id: 'pfx-disarming',
        word: 'Disarming',
        role: 'prefix',
        modIds: ['hndm-disarm'],
        validSlots: ['hands'],
        hiddenRarity: 'rare_mod',
        minLevel: 10,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'hands', 'status', 'control'],
    },
    {
        id: 'pfx-dazzling',
        word: 'Dazzling',
        role: 'prefix',
        modIds: ['hndm-blinding'],
        validSlots: ['hands'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 5,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'hands', 'status', 'control'],
    },
    // Emotional / utility prefix (head)
    {
        id: 'pfx-empathic',
        word: 'Empathic',
        role: 'prefix',
        modIds: ['hm-heart-focus'],
        validSlots: ['head'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'prefix', 'head', 'emotional', 'utility'],
    },
    // ─── Phase 153 expansion (2026-06-18): 30 new prefixes ───────────────────
    // Status-family weapon prefixes (each rides a new debuff backing mod)
    {
        id: 'pfx-slowing',
        word: 'Slowing',
        role: 'prefix',
        modIds: ['wm-slowing'],
        validSlots: ['weapon'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'weapon', 'status', 'control'],
    },
    {
        id: 'pfx-hunters',
        word: 'Hunter\'s',
        role: 'prefix',
        modIds: ['wm-marking'],
        validSlots: ['weapon'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'weapon', 'status', 'utility'],
    },
    {
        id: 'pfx-immolating',
        word: 'Immolating',
        role: 'prefix',
        modIds: ['wm-immolate'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 5,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'weapon', 'status', 'dot'],
    },
    {
        id: 'pfx-rending',
        word: 'Rending',
        role: 'prefix',
        modIds: ['wm-rending'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'weapon', 'status', 'dot'],
    },
    {
        id: 'pfx-plague',
        word: 'Plague',
        role: 'prefix',
        modIds: ['wm-plague-edge'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'weapon', 'status', 'dot'],
    },
    {
        id: 'pfx-withering',
        word: 'Withering',
        role: 'prefix',
        modIds: ['wm-withering'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 15,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'weapon', 'status', 'dot'],
    },
    {
        id: 'pfx-heartrending',
        word: 'Heartrending',
        role: 'prefix',
        modIds: ['wm-heartbreak'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'weapon', 'status', 'emotional'],
    },
    {
        id: 'pfx-toxic',
        word: 'Toxic',
        role: 'prefix',
        modIds: ['wm-toxic-edge'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 20,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'weapon', 'status', 'dot'],
    },
    {
        id: 'pfx-concussive',
        word: 'Concussive',
        role: 'prefix',
        modIds: ['wm-concussive'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 15,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'weapon', 'status', 'control'],
    },
    {
        id: 'pfx-petrifying',
        word: 'Petrifying',
        role: 'prefix',
        modIds: ['wm-petrifying'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 25,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'weapon', 'status', 'control'],
    },
    {
        id: 'pfx-terrifying',
        word: 'Terrifying',
        role: 'prefix',
        modIds: ['wm-terrorize'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 15,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'weapon', 'status', 'mental', 'control'],
    },
    {
        id: 'pfx-cursed',
        word: 'Cursed',
        role: 'prefix',
        modIds: ['wm-cursed-edge'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 20,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'weapon', 'status'],
    },
    {
        id: 'pfx-slumbering',
        word: 'Slumbering',
        role: 'prefix',
        modIds: ['wm-soporific'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 15,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'weapon', 'status', 'control'],
    },
    {
        id: 'pfx-hexing',
        word: 'Hexing',
        role: 'prefix',
        modIds: ['wm-hexing'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 20,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'weapon', 'status'],
    },
    // Status-family control prefixes (hands)
    {
        id: 'pfx-sapping',
        word: 'Sapping',
        role: 'prefix',
        modIds: ['hndm-sap'],
        validSlots: ['hands'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'hands', 'status', 'control'],
    },
    {
        id: 'pfx-ensnaring',
        word: 'Ensnaring',
        role: 'prefix',
        modIds: ['hndm-hobbling'],
        validSlots: ['hands'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'hands', 'status', 'control'],
    },
    {
        id: 'pfx-toppling',
        word: 'Toppling',
        role: 'prefix',
        modIds: ['hndm-toppling'],
        validSlots: ['hands'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'hands', 'status', 'control'],
    },
    {
        id: 'pfx-enfeebling',
        word: 'Enfeebling',
        role: 'prefix',
        modIds: ['hndm-enfeeble'],
        validSlots: ['hands'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 15,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'hands', 'status', 'control'],
    },
    {
        id: 'pfx-enthralling',
        word: 'Enthralling',
        role: 'prefix',
        modIds: ['hndm-enthrall'],
        validSlots: ['hands'],
        hiddenRarity: 'rare_mod',
        minLevel: 20,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'hands', 'status', 'emotional', 'control'],
    },
    // Multi-mod "amp + status" prefixes (status-effect doctrine payoff)
    {
        id: 'pfx-cruel',
        word: 'Cruel',
        role: 'prefix',
        modIds: ['wm-flat-damage', 'wm-rending'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'weapon', 'status', 'offense', 'dot'],
    },
    {
        id: 'pfx-malefic',
        word: 'Malefic',
        role: 'prefix',
        modIds: ['wm-status-amp', 'wm-cursed-edge'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 20,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'weapon', 'status'],
    },
    {
        id: 'pfx-pestilent',
        word: 'Pestilent',
        role: 'prefix',
        modIds: ['wm-plague-edge', 'wm-venom-coat'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 15,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'weapon', 'status', 'dot'],
    },
    // Defensive / utility prefixes (buff-backed)
    {
        id: 'pfx-oracular',
        word: 'Oracular',
        role: 'prefix',
        modIds: ['hm-oracle'],
        validSlots: ['head'],
        hiddenRarity: 'rare_mod',
        minLevel: 20,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'head', 'utility', 'mental'],
    },
    {
        id: 'pfx-openminded',
        word: 'Open',
        role: 'prefix',
        modIds: ['hm-open-mind'],
        validSlots: ['head'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 5,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'head', 'utility', 'mental'],
    },
    {
        id: 'pfx-bracing',
        word: 'Bracing',
        role: 'prefix',
        modIds: ['bm-defend-up'],
        validSlots: ['body'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'body', 'defense'],
    },
    {
        id: 'pfx-clearheaded',
        word: 'Clearheaded',
        role: 'prefix',
        modIds: ['armm-mind-resist'],
        validSlots: ['armor'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'armor', 'defense', 'mental'],
    },
    {
        id: 'pfx-unbreakable',
        word: 'Unbreakable',
        role: 'prefix',
        modIds: ['armm-stoic-bulwark'],
        validSlots: ['armor'],
        hiddenRarity: 'rare_mod',
        minLevel: 15,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'armor', 'defense'],
    },
    {
        id: 'pfx-attuned',
        word: 'Attuned',
        role: 'prefix',
        modIds: ['am-advantage-mind'],
        validSlots: ['accessory'],
        hiddenRarity: 'rare_mod',
        minLevel: 20,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'accessory', 'utility', 'mental'],
    },
    {
        id: 'pfx-paragon',
        word: 'Paragon',
        role: 'prefix',
        modIds: ['am-all-stats'],
        validSlots: ['accessory'],
        hiddenRarity: 'rare_mod',
        minLevel: 25,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'accessory', 'utility'],
    },
    {
        id: 'pfx-fleeting',
        word: 'Fleeting',
        role: 'prefix',
        modIds: ['fm-evasion-proc'],
        validSlots: ['feet'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-18',
        tags: ['affix', 'prefix', 'feet', 'defense', 'evasion'],
    },
];

// ─── Suffixes (trail the item name) ──────────────────────────────────────────

export const suffixes: Affix[] = [
    {
        id: 'sfx-of-the-bear',
        word: 'of the Bear',
        role: 'suffix',
        modIds: ['armm-vitality'],
        validSlots: ['armor'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-07',
        tags: ['affix', 'suffix', 'armor', 'defense'],
    },
    {
        id: 'sfx-of-the-ox',
        word: 'of the Ox',
        role: 'suffix',
        modIds: ['bm-vitality'],
        validSlots: ['body'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-07',
        tags: ['affix', 'suffix', 'body', 'defense'],
    },
    {
        id: 'sfx-of-clarity',
        word: 'of Clarity',
        role: 'suffix',
        modIds: ['hm-mind-gen'],
        validSlots: ['head'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 1,
        addedIn: '2026-06-07',
        tags: ['affix', 'suffix', 'head', 'mental', 'resource'],
    },
    {
        id: 'sfx-of-insight',
        word: 'of Insight',
        role: 'suffix',
        modIds: ['hm-insight'],
        validSlots: ['head'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 5,
        addedIn: '2026-06-07',
        tags: ['affix', 'suffix', 'head', 'mental'],
    },
    {
        id: 'sfx-of-warding',
        word: 'of Warding',
        role: 'suffix',
        modIds: ['armm-stoic'],
        validSlots: ['armor'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-07',
        tags: ['affix', 'suffix', 'armor', 'defense'],
    },
    {
        id: 'sfx-of-the-fortress',
        word: 'of the Fortress',
        role: 'suffix',
        modIds: ['bm-damage-reduction'],
        validSlots: ['body'],
        hiddenRarity: 'rare_mod',
        minLevel: 15,
        addedIn: '2026-06-07',
        tags: ['affix', 'suffix', 'body', 'defense'],
    },
    {
        id: 'sfx-of-thorns',
        word: 'of Thorns',
        role: 'suffix',
        modIds: ['bm-reflect'],
        validSlots: ['body'],
        hiddenRarity: 'rare_mod',
        minLevel: 10,
        addedIn: '2026-06-07',
        tags: ['affix', 'suffix', 'body', 'defense', 'proc'],
    },
    {
        id: 'sfx-of-the-fox',
        word: 'of the Fox',
        role: 'suffix',
        modIds: ['fm-physical-save'],
        validSlots: ['feet'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-07',
        tags: ['affix', 'suffix', 'feet', 'defense'],
    },
    {
        id: 'sfx-of-the-wind',
        word: 'of the Wind',
        role: 'suffix',
        modIds: ['fm-haste'],
        validSlots: ['feet'],
        hiddenRarity: 'rare_mod',
        minLevel: 20,
        addedIn: '2026-06-07',
        tags: ['affix', 'suffix', 'feet', 'utility'],
    },
    {
        id: 'sfx-of-precision',
        word: 'of Precision',
        role: 'suffix',
        modIds: ['hndm-crit-rate'],
        validSlots: ['hands'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-07',
        tags: ['affix', 'suffix', 'hands', 'crit'],
    },
    {
        id: 'sfx-of-the-duelist',
        word: 'of the Duelist',
        role: 'suffix',
        modIds: ['hndm-counter'],
        validSlots: ['hands'],
        hiddenRarity: 'rare_mod',
        minLevel: 20,
        addedIn: '2026-06-07',
        tags: ['affix', 'suffix', 'hands', 'proc'],
    },
    {
        id: 'sfx-of-the-leech',
        word: 'of the Leech',
        role: 'suffix',
        modIds: ['wm-lifesteal'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 1,
        addedIn: '2026-06-07',
        tags: ['affix', 'suffix', 'weapon', 'sustain'],
    },
    {
        id: 'sfx-of-ruin',
        word: 'of Ruin',
        role: 'suffix',
        modIds: ['wm-exploit'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 10,
        addedIn: '2026-06-07',
        tags: ['affix', 'suffix', 'weapon', 'offense'],
    },
    {
        id: 'sfx-of-mending',
        word: 'of Mending',
        role: 'suffix',
        modIds: ['am-regen'],
        validSlots: ['accessory'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-07',
        tags: ['affix', 'suffix', 'accessory', 'sustain'],
    },
    {
        id: 'sfx-of-the-heart',
        word: 'of the Heart',
        role: 'suffix',
        modIds: ['am-heart-focus'],
        validSlots: ['accessory'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-07',
        tags: ['affix', 'suffix', 'accessory', 'emotional'],
    },
    {
        id: 'sfx-of-the-triune',
        word: 'of the Triune',
        role: 'suffix',
        modIds: ['am-all-attunement'],
        validSlots: ['accessory'],
        hiddenRarity: 'rare_mod',
        minLevel: 25,
        addedIn: '2026-06-07',
        tags: ['affix', 'suffix', 'accessory', 'utility'],
    },
    // ─── Phase 151 expansion (2026-06-16): 20 new suffixes ───────────────────
    // Status-effect suffixes (weapon)
    {
        id: 'sfx-of-venom',
        word: 'of Venom',
        role: 'suffix',
        modIds: ['wm-venom-coat'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'weapon', 'status', 'dot'],
    },
    {
        id: 'sfx-of-frost',
        word: 'of Frost',
        role: 'suffix',
        modIds: ['wm-frost-brand'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'weapon', 'status', 'control'],
    },
    {
        id: 'sfx-of-the-tempest',
        word: 'of the Tempest',
        role: 'suffix',
        modIds: ['wm-storm-edge'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 15,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'weapon', 'status', 'control'],
    },
    {
        id: 'sfx-of-malice',
        word: 'of Malice',
        role: 'suffix',
        modIds: ['wm-status-amp'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 10,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'weapon', 'status'],
    },
    {
        id: 'sfx-of-the-serpent',
        word: 'of the Serpent',
        role: 'suffix',
        modIds: ['wm-mind-rend'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 20,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'weapon', 'mental', 'status'],
    },
    // Resource / skill suffixes
    {
        id: 'sfx-of-focus',
        word: 'of Focus',
        role: 'suffix',
        modIds: ['wm-mind-gen'],
        validSlots: ['weapon'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'weapon', 'resource'],
    },
    {
        id: 'sfx-of-momentum',
        word: 'of Momentum',
        role: 'suffix',
        modIds: ['fm-initiative-tokens'],
        validSlots: ['feet'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'feet', 'resource', 'initiative'],
    },
    {
        id: 'sfx-of-resolve',
        word: 'of Resolve',
        role: 'suffix',
        modIds: ['bm-heart-start'],
        validSlots: ['body'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'body', 'resource'],
    },
    // Defensive / resistance suffixes
    {
        id: 'sfx-of-the-bulwark',
        word: 'of the Bulwark',
        role: 'suffix',
        modIds: ['bm-barrier-proc'],
        validSlots: ['body'],
        hiddenRarity: 'rare_mod',
        minLevel: 10,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'body', 'defense', 'proc'],
    },
    {
        id: 'sfx-of-provocation',
        word: 'of Provocation',
        role: 'suffix',
        modIds: ['bm-taunt-proc'],
        validSlots: ['body'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 5,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'body', 'defense', 'control'],
    },
    {
        id: 'sfx-of-stone',
        word: 'of Stone',
        role: 'suffix',
        modIds: ['armm-body-resist'],
        validSlots: ['armor'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'armor', 'defense'],
    },
    {
        id: 'sfx-of-the-stalwart',
        word: 'of the Stalwart',
        role: 'suffix',
        modIds: ['armm-mhp'],
        validSlots: ['armor'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 5,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'armor', 'defense'],
    },
    {
        id: 'sfx-of-the-sentinel',
        word: 'of the Sentinel',
        role: 'suffix',
        modIds: ['hm-mind-resist'],
        validSlots: ['head'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'head', 'defense', 'mental'],
    },
    // Utility / sustain suffixes (accessory)
    {
        id: 'sfx-of-purity',
        word: 'of Purity',
        role: 'suffix',
        modIds: ['am-cleanse'],
        validSlots: ['accessory'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 5,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'accessory', 'sustain', 'status'],
    },
    {
        id: 'sfx-of-fortune',
        word: 'of Fortune',
        role: 'suffix',
        modIds: ['am-luck'],
        validSlots: ['accessory'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'accessory', 'utility', 'luck'],
    },
    {
        id: 'sfx-of-the-hex',
        word: 'of the Hex',
        role: 'suffix',
        modIds: ['am-status-amp'],
        validSlots: ['accessory'],
        hiddenRarity: 'rare_mod',
        minLevel: 10,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'accessory', 'status'],
    },
    {
        id: 'sfx-of-resilience',
        word: 'of Resilience',
        role: 'suffix',
        modIds: ['am-fortitude'],
        validSlots: ['accessory'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 5,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'accessory', 'defense'],
    },
    // Mobility / evasion suffixes (feet)
    {
        id: 'sfx-of-shadows',
        word: 'of Shadows',
        role: 'suffix',
        modIds: ['fm-stealth'],
        validSlots: ['feet'],
        hiddenRarity: 'rare_mod',
        minLevel: 10,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'feet', 'utility', 'evasion'],
    },
    {
        id: 'sfx-of-the-gambler',
        word: 'of the Gambler',
        role: 'suffix',
        modIds: ['fm-luck'],
        validSlots: ['feet'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 1,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'feet', 'utility', 'luck'],
    },
    // Disruption suffix (hands)
    {
        id: 'sfx-of-silence',
        word: 'of Silence',
        role: 'suffix',
        modIds: ['hndm-disarm'],
        validSlots: ['hands'],
        hiddenRarity: 'rare_mod',
        minLevel: 10,
        addedIn: '2026-06-16',
        tags: ['affix', 'suffix', 'hands', 'status', 'control'],
    },
    // ─── Phase 153 expansion (2026-06-18): 30 new suffixes ───────────────────
    // Status-family weapon suffixes (mirror the new debuff backing mods)
    {
        id: 'sfx-of-torpor',
        word: 'of Torpor',
        role: 'suffix',
        modIds: ['wm-slowing'],
        validSlots: ['weapon'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'weapon', 'status', 'control'],
    },
    {
        id: 'sfx-of-the-hunt',
        word: 'of the Hunt',
        role: 'suffix',
        modIds: ['wm-marking'],
        validSlots: ['weapon'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'weapon', 'status', 'utility'],
    },
    {
        id: 'sfx-of-cinders',
        word: 'of Cinders',
        role: 'suffix',
        modIds: ['wm-immolate'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 5,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'weapon', 'status', 'dot'],
    },
    {
        id: 'sfx-of-rending',
        word: 'of Rending',
        role: 'suffix',
        modIds: ['wm-rending'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'weapon', 'status', 'dot'],
    },
    {
        id: 'sfx-of-pestilence',
        word: 'of Pestilence',
        role: 'suffix',
        modIds: ['wm-plague-edge'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'weapon', 'status', 'dot'],
    },
    {
        id: 'sfx-of-decay',
        word: 'of Decay',
        role: 'suffix',
        modIds: ['wm-withering'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 15,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'weapon', 'status', 'dot'],
    },
    {
        id: 'sfx-of-heartache',
        word: 'of Heartache',
        role: 'suffix',
        modIds: ['wm-heartbreak'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'weapon', 'status', 'emotional'],
    },
    {
        id: 'sfx-of-blight',
        word: 'of Blight',
        role: 'suffix',
        modIds: ['wm-toxic-edge'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 20,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'weapon', 'status', 'dot'],
    },
    {
        id: 'sfx-of-concussion',
        word: 'of Concussion',
        role: 'suffix',
        modIds: ['wm-concussive'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 15,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'weapon', 'status', 'control'],
    },
    {
        id: 'sfx-of-petrifaction',
        word: 'of Petrifaction',
        role: 'suffix',
        modIds: ['wm-petrifying'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 25,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'weapon', 'status', 'control'],
    },
    {
        id: 'sfx-of-dread',
        word: 'of Dread',
        role: 'suffix',
        modIds: ['wm-terrorize'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 15,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'weapon', 'status', 'mental', 'control'],
    },
    {
        id: 'sfx-of-the-curse',
        word: 'of the Curse',
        role: 'suffix',
        modIds: ['wm-cursed-edge'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 20,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'weapon', 'status'],
    },
    {
        id: 'sfx-of-slumber',
        word: 'of Slumber',
        role: 'suffix',
        modIds: ['wm-soporific'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 15,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'weapon', 'status', 'control'],
    },
    {
        id: 'sfx-of-hexes',
        word: 'of Hexes',
        role: 'suffix',
        modIds: ['wm-hexing'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 20,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'weapon', 'status'],
    },
    // Status-family control suffixes (hands)
    {
        id: 'sfx-of-sapping',
        word: 'of Sapping',
        role: 'suffix',
        modIds: ['hndm-sap'],
        validSlots: ['hands'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'hands', 'status', 'control'],
    },
    {
        id: 'sfx-of-snares',
        word: 'of Snares',
        role: 'suffix',
        modIds: ['hndm-hobbling'],
        validSlots: ['hands'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'hands', 'status', 'control'],
    },
    {
        id: 'sfx-of-the-avalanche',
        word: 'of the Avalanche',
        role: 'suffix',
        modIds: ['hndm-toppling'],
        validSlots: ['hands'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'hands', 'status', 'control'],
    },
    {
        id: 'sfx-of-weariness',
        word: 'of Weariness',
        role: 'suffix',
        modIds: ['hndm-enfeeble'],
        validSlots: ['hands'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 15,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'hands', 'status', 'control'],
    },
    {
        id: 'sfx-of-enthrallment',
        word: 'of Enthrallment',
        role: 'suffix',
        modIds: ['hndm-enthrall'],
        validSlots: ['hands'],
        hiddenRarity: 'rare_mod',
        minLevel: 20,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'hands', 'status', 'emotional', 'control'],
    },
    // Multi-mod "amp + status" suffixes
    {
        id: 'sfx-of-cruelty',
        word: 'of Cruelty',
        role: 'suffix',
        modIds: ['wm-flat-damage', 'wm-rending'],
        validSlots: ['weapon'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'weapon', 'status', 'offense', 'dot'],
    },
    {
        id: 'sfx-of-affliction',
        word: 'of Affliction',
        role: 'suffix',
        modIds: ['wm-status-amp', 'wm-plague-edge'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 15,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'weapon', 'status', 'dot'],
    },
    {
        id: 'sfx-of-the-plaguebearer',
        word: 'of the Plaguebearer',
        role: 'suffix',
        modIds: ['wm-plague-edge', 'wm-venom-coat'],
        validSlots: ['weapon'],
        hiddenRarity: 'rare_mod',
        minLevel: 15,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'weapon', 'status', 'dot'],
    },
    // Defensive / utility suffixes (buff-backed)
    {
        id: 'sfx-of-prophecy',
        word: 'of Prophecy',
        role: 'suffix',
        modIds: ['hm-oracle'],
        validSlots: ['head'],
        hiddenRarity: 'rare_mod',
        minLevel: 20,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'head', 'utility', 'mental'],
    },
    {
        id: 'sfx-of-the-open-mind',
        word: 'of the Open Mind',
        role: 'suffix',
        modIds: ['hm-open-mind'],
        validSlots: ['head'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 5,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'head', 'utility', 'mental'],
    },
    {
        id: 'sfx-of-the-bastion',
        word: 'of the Bastion',
        role: 'suffix',
        modIds: ['bm-defend-up'],
        validSlots: ['body'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'body', 'defense'],
    },
    {
        id: 'sfx-of-lucidity',
        word: 'of Lucidity',
        role: 'suffix',
        modIds: ['armm-mind-resist'],
        validSlots: ['armor'],
        hiddenRarity: 'common_mod',
        minLevel: 1,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'armor', 'defense', 'mental'],
    },
    {
        id: 'sfx-of-the-immovable',
        word: 'of the Immovable',
        role: 'suffix',
        modIds: ['armm-stoic-bulwark'],
        validSlots: ['armor'],
        hiddenRarity: 'rare_mod',
        minLevel: 15,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'armor', 'defense'],
    },
    {
        id: 'sfx-of-attunement',
        word: 'of Attunement',
        role: 'suffix',
        modIds: ['am-advantage-mind'],
        validSlots: ['accessory'],
        hiddenRarity: 'rare_mod',
        minLevel: 20,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'accessory', 'utility', 'mental'],
    },
    {
        id: 'sfx-of-the-paragon',
        word: 'of the Paragon',
        role: 'suffix',
        modIds: ['am-all-stats'],
        validSlots: ['accessory'],
        hiddenRarity: 'rare_mod',
        minLevel: 25,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'accessory', 'utility'],
    },
    {
        id: 'sfx-of-quickening',
        word: 'of Quickening',
        role: 'suffix',
        modIds: ['fm-evasion-proc'],
        validSlots: ['feet'],
        hiddenRarity: 'uncommon_mod',
        minLevel: 10,
        addedIn: '2026-06-18',
        tags: ['affix', 'suffix', 'feet', 'defense', 'evasion'],
    },
];

// ─── Registry + helpers ──────────────────────────────────────────────────────

/** Every affix (prefixes followed by suffixes), in declaration order. */
export const allAffixes: ReadonlyArray<Affix> = [...prefixes, ...suffixes];

const affixRegistry = new Map<string, Affix>(allAffixes.map(a => [a.id, a]));

/** O(1) lookup by affix id. Returns `undefined` for unknown ids. */
export function getAffixById(id: string): Affix | undefined {
    return affixRegistry.get(id);
}

/**
 * Composes a decorated item name from a base name and optional affixes.
 *
 *   - prefix only → "<prefix.word> <base>"
 *   - suffix only → "<base> <suffix.word>"
 *   - both        → "<prefix.word> <base> <suffix.word>"
 *   - neither     → "<base>"
 *
 * Pure; never mutates its inputs.
 */
export function composeItemName(
    baseName: string,
    prefix?: Affix,
    suffix?: Affix,
): string {
    let name = baseName;
    if (prefix) name = `${prefix.word} ${name}`;
    if (suffix) name = `${name} ${suffix.word}`;
    return name;
}

/**
 * Returns every affix eligible for the given (slot, level, role):
 *   - `validSlots` includes `slot`, and
 *   - `minLevel <= level`.
 *
 * Declaration order is preserved so callers get a deterministic candidate
 * list (the factory then samples it with a seeded rng).
 */
export function affixesForSlot(
    slot: EquipmentSlot,
    level: number,
    role: AffixRole,
): Affix[] {
    const pool = role === 'prefix' ? prefixes : suffixes;
    return pool.filter(a => a.validSlots.includes(slot) && a.minLevel <= level);
}

/** Affix draw weights, reusing the hidden-mod rarity scale. */
export const AFFIX_RARITY_WEIGHTS: Record<HiddenModRarity, number> = {
    common_mod: 10,
    uncommon_mod: 3,
    rare_mod: 1,
};

/**
 * Slots that *apply* status to an opponent on a hit/attack — the offensive
 * status-application slots. Affixes on other slots that carry a `status` tag are
 * defensive/utility in nature (resist, cleanse, taunt) and are NOT the
 * doctrine's "apply and exploit status" payoff.
 */
const STATUS_APPLYING_SLOTS: ReadonlySet<EquipmentSlot> = new Set<EquipmentSlot>([
    'weapon',
    'hands',
]);

/** Tags that mark an affix as defensive/sustain intent even if `status`-tagged. */
const DEFENSIVE_AFFIX_TAGS: ReadonlySet<string> = new Set(['defense', 'sustain']);

/**
 * Phase 157 — is this affix an *offensive status-applying* affix?
 *
 * True only when the affix is `status`-tagged, can roll on a status-applying
 * slot (weapon/hands), and is not flagged defensive/sustain. This is the
 * discriminator the drop factory biases toward so affix rolls feed status-effect
 * play rather than flat-stat trading — without over-rewarding defensive `status`
 * affixes (cleanse, resist, taunt) that merely mention status.
 */
export function isOffensiveStatusAffix(affix: Affix): boolean {
    const tags = affix.tags ?? [];
    if (!tags.includes('status')) return false;
    if (tags.some(t => DEFENSIVE_AFFIX_TAGS.has(t))) return false;
    return affix.validSlots.some(s => STATUS_APPLYING_SLOTS.has(s));
}
