/**
 * Skill engine — pure resource and execution helpers for Spec 04.
 *
 * The combat resolver routes `action: 'skill'` through `executeSkill`. Every
 * helper here is pure: callers thread the updated state forward themselves.
 *
 * Resource economy (locked 2026-05-11):
 *   - Heart / Body / Mind tokens are generated by basic actions of the
 *     matching stance (attack hit = +3, attack miss = +1, defend = +5).
 *   - Fallacy / Paradox tokens are generated when the player uses a skill
 *     of that category.
 *   - Skill costs are spent against the same token pool. Multi-key costs
 *     implicitly require resonance — caller must hold ≥ each cost.
 */

import { Character } from '../Character/types';
import type { PhilosophicalAlignment } from '../Philosophy/types';
import { Enemy } from '../Enemy/types';
import { ActiveEffect, Effect } from '../Effects/types';
import { lookupEffect, applyEffect } from '../Effects';
import { applyDamage, heal } from '../Combat/health';
import { removeRandomBuff } from '../Combat/effects';
import { resolveEffectApplication } from '../Combat/resist';
import { Combatant, CombatState, Stance } from '../Combat/types';
import {
    RESOURCE_GENERATION,
    SKILL_STAT_MULTIPLIER,
} from '../Game/game-mechanics.constants';
import { Equipment, EquipmentSlot } from '../Items/types';
import { applyEquipmentGenerationBonus } from '../Items/equipment.engine';
import {
    CombatResources, ResourceCost, Skill, SkillCategory, SkillCombatEffects,
    SkillSpecialMechanic, SkillTier,
} from './types';
import { skillLibrary, getSkillById } from './skill.library';

// ─── Resource Generation ─────────────────────────────────────────────────────

/** Outcome of a basic action that drives token generation. */
export type BasicActionOutcome = 'hit' | 'miss' | 'defend';

/**
 * Returns a new `CombatResources` snapshot with the actor's stance token
 * topped up per the resource-generation table:
 *
 *   attack hit  → +3 of stance colour
 *   attack miss → +1 of stance colour
 *   defend      → +5 of stance colour
 *
 * Per Spec 05 Q10 / step 6, the optional `equipment` argument applies any
 * matching `generationBonus` entries from the wearer's equipped items on
 * top of the base table. Items without a `resourceInteraction` contribute
 * nothing — `equipment = undefined` reproduces pre-Spec 05 behaviour.
 *
 * Pure: input snapshot is not mutated.
 */
export function generateBasicActionResources(
    resources: CombatResources,
    stance: Stance,
    outcome: BasicActionOutcome,
    equipment?: Partial<Record<EquipmentSlot, Equipment>>,
): CombatResources {
    const amount =
        outcome === 'defend' ? RESOURCE_GENERATION.DEFEND
      : outcome === 'hit'    ? RESOURCE_GENERATION.ATTACK_HIT
      :                        RESOURCE_GENERATION.ATTACK_MISS;
    const base: CombatResources = { ...resources, [stance]: resources[stance] + amount };
    if (!equipment) return base;
    return applyEquipmentGenerationBonus(base, equipment, outcome);
}

/**
 * Adds 1 token of the philosophical resource matching the skill's category
 * (Fallacy or Paradox). Called after a skill resolves successfully.
 */
export function generatePhilosophicalResource(
    resources: CombatResources,
    category: SkillCategory,
): CombatResources {
    const key: keyof CombatResources = category === 'fallacy' ? 'fallacy' : 'paradox';
    return { ...resources, [key]: resources[key] + 1 };
}

// ─── Cost Checking & Spending ────────────────────────────────────────────────

const RESOURCE_KEYS: ReadonlyArray<keyof ResourceCost> =
    ['heart', 'body', 'mind', 'fallacy', 'paradox'];

/**
 * True iff every key listed in the skill's `resourceCost` has at least the
 * required amount in `resources`. Multi-key costs implicitly require
 * resonance — both pools must be funded simultaneously.
 */
export function canUseSkill(resources: CombatResources, skill: Skill): boolean {
    return RESOURCE_KEYS.every(key => {
        const cost = skill.resourceCost[key] ?? 0;
        return cost <= 0 || resources[key] >= cost;
    });
}

/**
 * Subtracts `cost` from `resources`. Throws if any key would go negative —
 * callers must guard with `canUseSkill` first.
 */
export function spendResources(
    resources: CombatResources,
    cost: ResourceCost,
): CombatResources {
    const next: CombatResources = { ...resources };
    for (const key of RESOURCE_KEYS) {
        const amount = cost[key] ?? 0;
        if (amount <= 0) continue;
        if (next[key] < amount) {
            throw new Error(`Insufficient ${key}: have ${next[key]}, need ${amount}`);
        }
        next[key] = next[key] - amount;
    }
    return next;
}

// ─── Damage Calculation ──────────────────────────────────────────────────────

/**
 * Skill damage formula:
 *
 *   damage = basePower
 *          + character.baseStats[scalingStat] × SKILL_STAT_MULTIPLIER × (scalingMultiplier ?? 1)
 *
 * The actor's baseStats are read directly (not effective stats) — skill
 * scaling is intentionally simpler than the basic-attack rolls so balancing
 * stays predictable. Stat-modifier effects influence the basic-attack path,
 * not the skill scaling path. `scalingMultiplier` lets individual skills like
 * Appeal to Pity amplify the stat term without warping `basePower`.
 */
export function calculateSkillDamage(actor: Combatant, skill: Skill): number {
    const multiplier = skill.scalingMultiplier ?? 1;
    return Math.max(
        0,
        Math.round(
            skill.basePower
            + actor.baseStats[skill.scalingStat] * SKILL_STAT_MULTIPLIER * multiplier,
        ),
    );
}

/**
 * Returns the philosophical category the skill should generate on use.
 * Tier 1 / 2 skills generate their own category (Fallacy → Fallacy, Paradox
 * → Paradox). Tier 3 skills already consumed a philosophical token to fire,
 * so they generate the OPPOSING type — Fallacy → Paradox, Paradox → Fallacy.
 * This drives the late-combat skill chain described in Spec 04b.
 */
export function philosophicalCategoryFor(skill: Skill): SkillCategory {
    if (skill.tier === 3) {
        return skill.category === 'fallacy' ? 'paradox' : 'fallacy';
    }
    return skill.category;
}

// ─── Skill Learning (Spec 06 Q7 / Phase 30) ──────────────────────────────────

/**
 * Default minimum character level for a skill that didn't author an explicit
 * `learningRequirement`. Mirrors the preset progression: T1 skills come for
 * free, T2 unlocks around mid-game, T3 deep into late-game.
 */
function defaultLevelForTier(tier: SkillTier): number {
    return tier === 1 ? 1 : tier === 2 ? 5 : 10;
}

/**
 * True iff `character` meets every clause on `skill.learningRequirement`
 * (level minimum, optional stat threshold, optional prerequisite skill,
 * optional alignment gate). When the skill has no explicit requirement,
 * falls back to a tier-derived level minimum per `defaultLevelForTier`.
 *
 * @param alignment - Phase 46 optional. When provided AND the skill carries
 *   `requiresAlignment`, the gate must pass. When the skill carries the
 *   gate but no alignment is passed in, the requirement fails (parallel to
 *   the dialogue `requiresAlignment` semantic).
 */
export function meetsLearningRequirement(
    character: Pick<Character, 'level' | 'baseStats' | 'knownSkills'>,
    skill: Skill,
    alignment?: PhilosophicalAlignment,
): boolean {
    const req = skill.learningRequirement ?? { level: defaultLevelForTier(skill.tier) };
    if (character.level < req.level) return false;
    if (req.statRequirementType && req.statRequirementValue !== undefined) {
        if (character.baseStats[req.statRequirementType] < req.statRequirementValue) {
            return false;
        }
    }
    if (req.prerequisiteSkill && !character.knownSkills.includes(req.prerequisiteSkill)) {
        return false;
    }
    if (req.requiresAlignment) {
        if (!alignment) return false;
        const { axis, op, value } = req.requiresAlignment;
        const v = alignment[axis];
        if (op === 'gte' && !(v >= value)) return false;
        if (op === 'lte' && !(v <= value)) return false;
    }
    return true;
}

/**
 * Returns every entry in `skillLibrary` that the character has not already
 * learned AND meets the learning requirement for. Order matches the library
 * order so the UI can show a stable list across calls.
 *
 * @param alignment - Phase 46 optional. Threaded into `meetsLearningRequirement`
 *   so alignment-gated skills are filtered out when the character's
 *   alignment doesn't match (or isn't provided).
 */
export function getAvailableSkills(
    character: Pick<Character, 'level' | 'baseStats' | 'knownSkills'>,
    alignment?: PhilosophicalAlignment,
): Skill[] {
    return skillLibrary.filter(s =>
        !character.knownSkills.includes(s.id)
        && meetsLearningRequirement(character, s, alignment),
    );
}

/**
 * Appends `skillId` to `character.knownSkills` when the skill exists, is not
 * already known, and the character meets its learning requirement. Pure;
 * returns the unchanged character (same reference) on any guard miss.
 *
 * @param alignment - Phase 46 optional. Threaded into `meetsLearningRequirement`
 *   so alignment-gated skills can only be learned by characters whose
 *   alignment matches the gate.
 */
export function learnSkill(
    character: Character,
    skillId: string,
    alignment?: PhilosophicalAlignment,
): Character {
    if (character.knownSkills.includes(skillId)) return character;
    const skill = getSkillById(skillId);
    if (!skill) return character;
    if (!meetsLearningRequirement(character, skill, alignment)) return character;
    return {
        ...character,
        knownSkills: [...character.knownSkills, skillId],
    };
}

// ─── Skill Execution ─────────────────────────────────────────────────────────

/** One discrete thing that happened while a skill resolved. */
export type SkillEvent =
    | { kind: 'damage';
        skillId: string;
        target: 'self' | 'enemy';
        amount: number;
        hpBefore: number;
        hpAfter: number }
    | { kind: 'heal';
        skillId: string;
        target: 'self' | 'enemy';
        amount: number;
        hpBefore: number;
        hpAfter: number }
    | { kind: 'effect-applied';
        skillId: string;
        appliedTo: 'self' | 'enemy';
        effect: Effect;
        message: string }
    | { kind: 'effect-resisted';
        skillId: string;
        appliedTo: 'self' | 'enemy';
        effect: Effect;
        message: string }
    | { kind: 'effect-rebounded';
        skillId: string;
        effect: Effect;
        message: string }
    | { kind: 'buff-stripped';
        skillId: string;
        target: 'self' | 'enemy';
        effect: Effect | null }
    | { kind: 'buff-converted';
        skillId: string;
        effect: Effect | null;
        message: string }
    | { kind: 'resources-spent';
        skillId: string;
        cost: ResourceCost }
    | { kind: 'philosophical-generated';
        skillId: string;
        category: SkillCategory };

/** Result of `executeSkill`. */
export interface SkillResolution {
    state: CombatState;
    events: SkillEvent[];
}

/** Lookup helper used by `executeSkill` to resolve a skill ID against an actor. */
export interface SkillLookup {
    (skillId: string): Skill | undefined;
}

/**
 * Runs a skill end-to-end against the current `CombatState`:
 *
 *   1. Validate the skill is equipped (player) or in the enemy's rotation.
 *   2. Validate `canUseSkill` (resources sufficient) — throws otherwise.
 *   3. Apply damage / heal based on `targetType`.
 *   4. Resolve each `combatEffects` payload through `resolveEffectApplication`
 *      so resist tier matches the skill's `tier`.
 *   5. Spend the resource cost.
 *   6. Generate one Fallacy or Paradox token from the skill's category.
 *
 * The resolver — not this function — is responsible for emitting `RoundEvent`s
 * to the broader combatEvents stream; it adapts our `SkillEvent[]` into that
 * shape.
 *
 * Phase 49 — `casterSide` decides which side is firing the skill. Defaults
 * to `'player'` for back-compat with the pre-Phase-49 call site at
 * `src/Combat/phases/scenario.ts`. When `'enemy'`, the enemy is the caster
 * and the player is the target; `skill.targetType` is interpreted relative
 * to the caster (`'self'` → caster's effects; `'enemy'` → opposing side).
 * Enemy-cast skills are validated against `Enemy.skills?` rather than
 * `Character.equippedSkills`. Resource handling stays uniform — the caller
 * is responsible for passing a sentinel `combatResources` for the enemy
 * path (per D2 in plan/phases/phase_49_enemy_skill_caster.md).
 *
 * @throws if the skill is not equipped (player path) or not in the enemy's
 *   rotation (enemy path), not found in the lookup, or the caster cannot
 *   afford it.
 */
export function executeSkill(
    state: CombatState,
    skillId: string,
    lookupSkill: SkillLookup,
    casterSide: 'player' | 'enemy' = 'player',
): SkillResolution {
    const isPlayerCaster = casterSide === 'player';
    const caster: Combatant = isPlayerCaster ? state.player : state.enemy;
    const target: Combatant = isPlayerCaster ? state.enemy : state.player;

    if (isPlayerCaster) {
        if (!(caster as Character).equippedSkills.includes(skillId)) {
            throw new Error(`Skill '${skillId}' is not equipped.`);
        }
    } else {
        const rotation = (caster as Enemy).skills ?? [];
        if (!rotation.some(s => s.id === skillId)) {
            throw new Error(`Skill '${skillId}' is not in the enemy's rotation.`);
        }
    }

    const skill = lookupSkill(skillId);
    if (!skill) {
        throw new Error(`Skill '${skillId}' not found in library.`);
    }

    if (!canUseSkill(state.combatResources, skill)) {
        throw new Error(`Insufficient resources for '${skill.name}'.`);
    }

    const events: SkillEvent[] = [];

    let workingCaster: Combatant = caster;
    let workingTarget: Combatant = target;

    const damage = calculateSkillDamage(workingCaster, skill);

    if (damage > 0) {
        if (skill.targetType === 'enemy') {
            const hpBefore = workingTarget.health;
            workingTarget = applyDamage(workingTarget, damage);
            events.push({
                kind: 'damage', skillId, target: 'enemy',
                amount: damage, hpBefore, hpAfter: workingTarget.health,
            });
        } else {
            const hpBefore = workingCaster.health;
            workingCaster = heal(workingCaster, damage);
            events.push({
                kind: 'heal', skillId, target: 'self',
                amount: damage, hpBefore, hpAfter: workingCaster.health,
            });
        }
    }

    for (const payload of skill.combatEffects ?? []) {
        const result = applySkillEffect(
            payload, skill, workingCaster, workingTarget, state.round,
        );
        workingCaster = result.caster;
        workingTarget = result.target;
        events.push(...result.events);
    }

    for (const mechanic of skill.specialMechanics ?? []) {
        const result = applySpecialMechanic(
            mechanic, skill, workingCaster, workingTarget, state.round,
        );
        workingCaster = result.caster;
        workingTarget = result.target;
        events.push(...result.events);
    }

    const genCategory = philosophicalCategoryFor(skill);
    const nextResources = generatePhilosophicalResource(
        spendResources(state.combatResources, skill.resourceCost),
        genCategory,
    );
    events.push({ kind: 'resources-spent', skillId, cost: skill.resourceCost });
    events.push({ kind: 'philosophical-generated', skillId, category: genCategory });

    const nextPlayer = (isPlayerCaster ? workingCaster : workingTarget) as Character;
    const nextEnemy  = (isPlayerCaster ? workingTarget : workingCaster) as Enemy;

    return {
        state: {
            ...state,
            player: nextPlayer,
            enemy:  nextEnemy,
            combatResources: nextResources,
        },
        events,
    };
}

interface SkillEffectResult {
    caster: Combatant;
    target: Combatant;
    events: SkillEvent[];
}

/**
 * Routes a single `SkillCombatEffects` payload through the Spec 03
 * `resolveEffectApplication` resolver and lands the outcome on the correct
 * combatant. Tier-driven resist behaviour is inherited from the underlying
 * effect definition (Tier 1 auto, Tier 2 resisted, Tier 3 nat-20 only).
 *
 * `payload.intensity` and `payload.duration` override the effect's default
 * stack/duration so skills like Liar's Echo (+2 intensity, 2-round mark) and
 * Sorites' Cascade (intensity-2 bleed) can lean on the same library entry as
 * the proc system without warping the underlying effect definition.
 *
 * Phase 49 — caster-agnostic. `payload.appliedTo === 'self'` routes to
 * `caster.effects`; `'enemy'` routes to `target.effects` (the opposing
 * side, regardless of which Combatant subtype that is).
 */
function applySkillEffect(
    payload: SkillCombatEffects,
    skill: Skill,
    caster: Combatant,
    target: Combatant,
    round: number,
): SkillEffectResult {
    const events: SkillEvent[] = [];
    const effect = lookupEffect(payload.effectId);
    if (!effect) {
        return { caster, target, events };
    }

    const targetIsSelf = payload.appliedTo === 'self';
    const effectTarget: Combatant = targetIsSelf ? caster : target;
    const intensityOverride = payload.intensity;
    const durationOverride  = payload.duration;

    const built = buildActiveEffect(effect, round, intensityOverride, durationOverride);
    const result = resolveEffectApplication(
        effectTarget,
        built,
        effect.type,
        caster.baseStats.heart,
    );

    // When the skill payload explicitly overrides duration we must apply in
    // `additive` mode so the override survives the apply path, which otherwise
    // resets to `effect.duration` on first application. The override value is
    // also the value to write.
    const buildApplyOptions = (intensity: number, duration: number) => {
        if (durationOverride !== undefined) {
            return {
                intensityDelta: intensity,
                durationMode:   'additive' as const,
                durationDelta:  duration,
            };
        }
        return {
            intensityDelta: intensity,
            durationDelta:  duration,
        };
    };

    if (result.rebounded && result.activeEffect) {
        const reboundIntensity = result.activeEffect.intensity ?? intensityOverride ?? 1;
        const reboundDuration  = result.activeEffect.remainingDuration ?? durationOverride ?? effect.duration;
        // Rebound always lands on the caster (the side that originated the skill).
        const reboundedEffects = applyEffect(
            caster.effects, effect, round,
            { ...buildApplyOptions(reboundIntensity, reboundDuration), sourceId: caster.id },
        );
        events.push({
            kind: 'effect-rebounded', skillId: skill.id, effect, message: result.message,
        });
        return {
            caster: { ...caster, effects: reboundedEffects.activeEffects } as Combatant,
            target,
            events,
        };
    }

    if (!result.success) {
        events.push({
            kind: 'effect-resisted', skillId: skill.id,
            appliedTo: targetIsSelf ? 'self' : 'enemy',
            effect, message: result.message,
        });
        return { caster, target, events };
    }

    const appliedIntensity = result.activeEffect?.intensity ?? intensityOverride ?? 1;
    const appliedDuration  = result.activeEffect?.remainingDuration ?? durationOverride ?? effect.duration;

    const applied = applyEffect(
        effectTarget.effects, effect, round,
        { ...buildApplyOptions(appliedIntensity, appliedDuration), sourceId: caster.id },
    );

    events.push({
        kind: 'effect-applied', skillId: skill.id,
        appliedTo: targetIsSelf ? 'self' : 'enemy',
        effect, message: result.message,
    });

    if (targetIsSelf) {
        return {
            caster: { ...caster, effects: applied.activeEffects } as Combatant,
            target,
            events,
        };
    }
    return {
        caster,
        target: { ...target, effects: applied.activeEffects } as Combatant,
        events,
    };
}

function buildActiveEffect(
    effect: Effect,
    round: number,
    intensityOverride?: number,
    durationOverride?: number,
): ActiveEffect {
    return {
        effectId:          effect.id,
        remainingDuration: durationOverride  ?? effect.duration,
        intensity:         intensityOverride ?? 1,
        appliedAt:         round,
        tier:              effect.tier,
        resistedBy:        effect.resistedBy,
        resistDR:          effect.resistDR,
    };
}

// ─── Special Mechanics ───────────────────────────────────────────────────────

/**
 * Resolves a `SkillSpecialMechanic` (buff-strip, conversion, secondary heal,
 * etc.) against the current working player / enemy snapshots and returns the
 * updated snapshots plus any `SkillEvent`s the resolver should forward to
 * the combat event stream.
 *
 * Mechanics run AFTER `combatEffects` so that, for example, Ship of Theseus
 * sees the same buff list a player can observe in the CLI before this round
 * resolves.
 */
function applySpecialMechanic(
    mechanic: SkillSpecialMechanic,
    skill: Skill,
    caster: Combatant,
    target: Combatant,
    round: number,
): SkillEffectResult {
    const events: SkillEvent[] = [];

    switch (mechanic.kind) {
        case 'bypass_defense':
            return { caster, target, events };

        case 'strip_random_buff': {
            if (mechanic.appliedTo === 'enemy') {
                const { target: nextTarget, removed } = removeRandomBuff(target);
                events.push({
                    kind: 'buff-stripped', skillId: skill.id, target: 'enemy',
                    effect: removed ? lookupEffect(removed.effectId) ?? null : null,
                });
                return { caster, target: nextTarget, events };
            }
            const { target: nextCaster, removed } = removeRandomBuff(caster);
            events.push({
                kind: 'buff-stripped', skillId: skill.id, target: 'self',
                effect: removed ? lookupEffect(removed.effectId) ?? null : null,
            });
            return { caster: nextCaster, target, events };
        }

        case 'convert_enemy_buff_to_self': {
            const { target: nextTarget, removed } = removeRandomBuff(target);
            if (!removed) {
                events.push({
                    kind: 'buff-converted', skillId: skill.id, effect: null,
                    message: 'No buffs to convert.',
                });
                return { caster, target: nextTarget, events };
            }
            const effect = lookupEffect(removed.effectId);
            if (!effect) {
                events.push({
                    kind: 'buff-converted', skillId: skill.id, effect: null,
                    message: 'Buff stripped but unknown — could not transfer.',
                });
                return { caster, target: nextTarget, events };
            }
            const applied = applyEffect(caster.effects, effect, round, {
                intensityDelta: removed.intensity ?? 1,
                durationDelta:  removed.remainingDuration,
                sourceId:       caster.id,
            });
            events.push({
                kind: 'buff-converted', skillId: skill.id, effect,
                message: `${effect.name} converted onto the caster.`,
            });
            return {
                caster: { ...caster, effects: applied.activeEffects } as Combatant,
                target: nextTarget,
                events,
            };
        }

        case 'secondary_heal_self': {
            const multiplier = mechanic.multiplier ?? 1;
            const amount = Math.max(
                0,
                Math.round(caster.baseStats[mechanic.stat] * SKILL_STAT_MULTIPLIER * multiplier),
            );
            if (amount <= 0) {
                return { caster, target, events };
            }
            const hpBefore = caster.health;
            const nextCaster = heal(caster, amount);
            events.push({
                kind: 'heal', skillId: skill.id, target: 'self',
                amount, hpBefore, hpAfter: nextCaster.health,
            });
            return { caster: nextCaster, target, events };
        }
    }
}
