/**
 * Skill engine — pure resource and execution helpers for Spec 04.
 *
 * The combat resolver routes `action: 'skill'` through `executeSkill`. Every
 * helper here is pure: callers thread the updated state forward themselves.
 *
 * Resource economy (locked 2026-05-11):
 *   - Heart / Body / Mind tokens are generated by basic actions of the
 *     matching stance (attack hit = +3, attack miss = +1, defend = +5).
 *   - Fallacy / Paradox tokens are generated when the player uses a skill
 *     of that category.
 *   - Skill costs are spent against the same token pool. Multi-key costs
 *     implicitly require resonance — caller must hold ≥ each cost.
 */

import { Character } from '../Character/types';
import { Enemy } from '../Enemy/types';
import { ActiveEffect, Effect } from '../Effects/types';
import { lookupEffect, applyEffect } from '../Effects';
import { applyDamage, heal } from '../Combat/health';
import { resolveEffectApplication } from '../Combat/resist';
import { Combatant, CombatState, Stance } from '../Combat/types';
import {
    RESOURCE_GENERATION,
    SKILL_STAT_MULTIPLIER,
} from '../Game/game-mechanics.constants';
import {
    CombatResources, ResourceCost, Skill, SkillCategory, SkillCombatEffects,
} from './types';

// ─── Resource Generation ─────────────────────────────────────────────────────

/** Outcome of a basic action that drives token generation. */
export type BasicActionOutcome = 'hit' | 'miss' | 'defend';

/**
 * Returns a new `CombatResources` snapshot with the actor's stance token
 * topped up per the resource-generation table:
 *
 *   attack hit  → +3 of stance colour
 *   attack miss → +1 of stance colour
 *   defend      → +5 of stance colour
 *
 * Pure: input snapshot is not mutated.
 */
export function generateBasicActionResources(
    resources: CombatResources,
    stance: Stance,
    outcome: BasicActionOutcome,
): CombatResources {
    const amount =
        outcome === 'defend' ? RESOURCE_GENERATION.DEFEND
      : outcome === 'hit'    ? RESOURCE_GENERATION.ATTACK_HIT
      :                        RESOURCE_GENERATION.ATTACK_MISS;
    return { ...resources, [stance]: resources[stance] + amount };
}

/**
 * Adds 1 token of the philosophical resource matching the skill's category
 * (Fallacy or Paradox). Called after a skill resolves successfully.
 */
export function generatePhilosophicalResource(
    resources: CombatResources,
    category: SkillCategory,
): CombatResources {
    const key: keyof CombatResources = category === 'fallacy' ? 'fallacy' : 'paradox';
    return { ...resources, [key]: resources[key] + 1 };
}

// ─── Cost Checking & Spending ────────────────────────────────────────────────

const RESOURCE_KEYS: ReadonlyArray<keyof ResourceCost> =
    ['heart', 'body', 'mind', 'fallacy', 'paradox'];

/**
 * True iff every key listed in the skill's `resourceCost` has at least the
 * required amount in `resources`. Multi-key costs implicitly require
 * resonance — both pools must be funded simultaneously.
 */
export function canUseSkill(resources: CombatResources, skill: Skill): boolean {
    return RESOURCE_KEYS.every(key => {
        const cost = skill.resourceCost[key] ?? 0;
        return cost <= 0 || resources[key] >= cost;
    });
}

/**
 * Subtracts `cost` from `resources`. Throws if any key would go negative —
 * callers must guard with `canUseSkill` first.
 */
export function spendResources(
    resources: CombatResources,
    cost: ResourceCost,
): CombatResources {
    const next: CombatResources = { ...resources };
    for (const key of RESOURCE_KEYS) {
        const amount = cost[key] ?? 0;
        if (amount <= 0) continue;
        if (next[key] < amount) {
            throw new Error(`Insufficient ${key}: have ${next[key]}, need ${amount}`);
        }
        next[key] = next[key] - amount;
    }
    return next;
}

// ─── Damage Calculation ──────────────────────────────────────────────────────

/**
 * Skill damage formula:
 *
 *   damage = basePower + character.baseStats[scalingStat] × SKILL_STAT_MULTIPLIER
 *
 * The actor's baseStats are read directly (not effective stats) — skill
 * scaling is intentionally simpler than the basic-attack rolls so balancing
 * stays predictable. Stat-modifier effects influence the basic-attack path,
 * not the skill scaling path.
 */
export function calculateSkillDamage(actor: Combatant, skill: Skill): number {
    return Math.max(
        0,
        Math.round(skill.basePower + actor.baseStats[skill.scalingStat] * SKILL_STAT_MULTIPLIER),
    );
}

// ─── Skill Execution ─────────────────────────────────────────────────────────

/** One discrete thing that happened while a skill resolved. */
export type SkillEvent =
    | { kind: 'damage';
        skillId: string;
        target: 'self' | 'enemy';
        amount: number;
        hpBefore: number;
        hpAfter: number }
    | { kind: 'heal';
        skillId: string;
        target: 'self' | 'enemy';
        amount: number;
        hpBefore: number;
        hpAfter: number }
    | { kind: 'effect-applied';
        skillId: string;
        appliedTo: 'self' | 'enemy';
        effect: Effect;
        message: string }
    | { kind: 'effect-resisted';
        skillId: string;
        appliedTo: 'self' | 'enemy';
        effect: Effect;
        message: string }
    | { kind: 'effect-rebounded';
        skillId: string;
        effect: Effect;
        message: string }
    | { kind: 'resources-spent';
        skillId: string;
        cost: ResourceCost }
    | { kind: 'philosophical-generated';
        skillId: string;
        category: SkillCategory };

/** Result of `executeSkill`. */
export interface SkillResolution {
    state: CombatState;
    events: SkillEvent[];
}

/** Lookup helper used by `executeSkill` to resolve a skill ID against an actor. */
export interface SkillLookup {
    (skillId: string): Skill | undefined;
}

/**
 * Runs a skill end-to-end against the current `CombatState`:
 *
 *   1. Validate the skill is equipped and known.
 *   2. Validate `canUseSkill` (resources sufficient) — throws otherwise.
 *   3. Apply damage / heal based on `targetType`.
 *   4. Resolve each `combatEffects` payload through `resolveEffectApplication`
 *      so resist tier matches the skill's `tier`.
 *   5. Spend the resource cost.
 *   6. Generate one Fallacy or Paradox token from the skill's category.
 *
 * The resolver — not this function — is responsible for emitting `RoundEvent`s
 * to the broader combatEvents stream; it adapts our `SkillEvent[]` into that
 * shape.
 *
 * @throws if the skill is not equipped, not found in the lookup, or the
 *   actor cannot afford it.
 */
export function executeSkill(
    state: CombatState,
    skillId: string,
    lookupSkill: SkillLookup,
): SkillResolution {
    const player = state.player;

    if (!player.equippedSkills.includes(skillId)) {
        throw new Error(`Skill '${skillId}' is not equipped.`);
    }

    const skill = lookupSkill(skillId);
    if (!skill) {
        throw new Error(`Skill '${skillId}' not found in library.`);
    }

    if (!canUseSkill(state.combatResources, skill)) {
        throw new Error(`Insufficient resources for '${skill.name}'.`);
    }

    const events: SkillEvent[] = [];

    let workingPlayer: Character = player;
    let workingEnemy: Enemy = state.enemy;

    const targetIsEnemy = skill.targetType === 'enemy';
    const damage = calculateSkillDamage(workingPlayer, skill);

    if (damage > 0) {
        if (targetIsEnemy) {
            const hpBefore = workingEnemy.health;
            workingEnemy = applyDamage(workingEnemy, damage);
            events.push({
                kind: 'damage', skillId, target: 'enemy',
                amount: damage, hpBefore, hpAfter: workingEnemy.health,
            });
        } else {
            const hpBefore = workingPlayer.health;
            workingPlayer = heal(workingPlayer, damage);
            events.push({
                kind: 'heal', skillId, target: 'self',
                amount: damage, hpBefore, hpAfter: workingPlayer.health,
            });
        }
    }

    for (const payload of skill.combatEffects ?? []) {
        const result = applySkillEffect(
            payload, skill, workingPlayer, workingEnemy, state.round,
        );
        workingPlayer = result.player;
        workingEnemy  = result.enemy;
        events.push(...result.events);
    }

    const nextResources = generatePhilosophicalResource(
        spendResources(state.combatResources, skill.resourceCost),
        skill.category,
    );
    events.push({ kind: 'resources-spent', skillId, cost: skill.resourceCost });
    events.push({ kind: 'philosophical-generated', skillId, category: skill.category });

    return {
        state: {
            ...state,
            player: workingPlayer,
            enemy:  workingEnemy,
            combatResources: nextResources,
        },
        events,
    };
}

interface SkillEffectResult {
    player: Character;
    enemy: Enemy;
    events: SkillEvent[];
}

/**
 * Routes a single `SkillCombatEffects` payload through the Spec 03
 * `resolveEffectApplication` resolver and lands the outcome on the correct
 * combatant. Tier-driven resist behaviour is inherited from the underlying
 * effect definition (Tier 1 auto, Tier 2 resisted, Tier 3 nat-20 only).
 */
function applySkillEffect(
    payload: SkillCombatEffects,
    skill: Skill,
    player: Character,
    enemy: Enemy,
    round: number,
): SkillEffectResult {
    const events: SkillEvent[] = [];
    const effect = lookupEffect(payload.effectId);
    if (!effect) {
        return { player, enemy, events };
    }

    const targetIsSelf = payload.appliedTo === 'self';
    const target: Combatant = targetIsSelf ? player : enemy;

    const built = buildActiveEffect(effect, round);
    const result = resolveEffectApplication(
        target,
        built,
        effect.type,
        player.baseStats.heart,
    );

    if (result.rebounded && result.activeEffect) {
        const reboundedEffects = applyEffect(
            player.effects, effect, round,
            { intensityDelta: result.activeEffect.intensity ?? 1 },
        );
        events.push({
            kind: 'effect-rebounded', skillId: skill.id, effect, message: result.message,
        });
        return {
            player: { ...player, effects: reboundedEffects.activeEffects },
            enemy,
            events,
        };
    }

    if (!result.success) {
        events.push({
            kind: 'effect-resisted', skillId: skill.id,
            appliedTo: targetIsSelf ? 'self' : 'enemy',
            effect, message: result.message,
        });
        return { player, enemy, events };
    }

    const applied = applyEffect(target.effects, effect, round, {
        intensityDelta: result.activeEffect?.intensity ?? 1,
        durationDelta:  result.activeEffect?.remainingDuration ?? effect.duration,
    });

    events.push({
        kind: 'effect-applied', skillId: skill.id,
        appliedTo: targetIsSelf ? 'self' : 'enemy',
        effect, message: result.message,
    });

    if (targetIsSelf) {
        return {
            player: { ...player, effects: applied.activeEffects },
            enemy,
            events,
        };
    }
    return {
        player,
        enemy: { ...enemy, effects: applied.activeEffects },
        events,
    };
}

function buildActiveEffect(effect: Effect, round: number): ActiveEffect {
    return {
        effectId:          effect.id,
        remainingDuration: effect.duration,
        intensity:         1,
        appliedAt:         round,
        tier:              effect.tier,
        resistedBy:        effect.resistedBy,
        resistDR:          effect.resistDR,
    };
}
