/**
 * Skills System Types
 * Skills come in two categories: fallacies and paradoxes, and run on a five-
 * resource resonance economy (heart / body / mind / fallacy / paradox). See
 * `specs/04-skills-engine.md` for the full economy design.
 */

/**
 * Philosophical aspect alignment for skills
 * Determines which base stat the skill scales with and which combat type it uses.
 * - 'body': Physical/strength-based skills
 * - 'mind': Mental/intelligence-based skills
 * - 'heart': Emotional/charisma-based skills
 */
export type SkillsStatType = 'body' | 'mind' | 'heart';

/**
 * Skill category type
 * - 'fallacy': Skills based on logical fallacies (generate ⚖ on use)
 * - 'paradox': Skills based on philosophical paradoxes (generate ∞ on use)
 */
export type SkillCategory = 'fallacy' | 'paradox';

/**
 * Tier of a skill — mirrors the effect tier system. Drives the resist tier
 * used when a skill applies a `combatEffects` payload through the Spec 03
 * machinery (Tier 1 auto-applies, Tier 2 resisted, Tier 3 only nat-20 repels).
 */
export type SkillTier = 1 | 2 | 3;

/**
 * Targeting scope for a skill effect.
 * - `'self'`  — the caster.
 * - `'enemy'` — the current opponent.
 * Multi-combatant targeting is deferred to Spec 07.
 */
export type SkillTarget = 'self' | 'enemy';

/**
 * Resource cost paid to use a skill. Each key maps to a `combatResources`
 * counter. Multi-key costs implicitly require resonance — the caster must
 * hold ≥ the listed amount of each resource simultaneously, and spending
 * the tokens dissolves the resonance state.
 */
export interface ResourceCost {
    heart?: number;
    body?: number;
    mind?: number;
    fallacy?: number;
    paradox?: number;
}

/**
 * Per-combat resource counters lived on `CombatState`. Generated by basic
 * actions (heart/body/mind from stance attacks/defends) and by skill use
 * (fallacy/paradox from skill category).
 */
export interface CombatResources {
    heart: number;
    body: number;
    mind: number;
    fallacy: number;
    paradox: number;
}

/**
 * Learning requirement for a skill
 * Defines the prerequisites a character must meet to learn this skill.
 * Moral-alignment gates (Spec 10) are deferred.
 *
 * @property level - Minimum character level required to learn this skill
 * @property statRequirementType - Optional: which base stat must meet the requirement (body/mind/heart)
 * @property statRequirementValue - Optional: minimum value for the specified stat
 * @property prerequisiteSkill - Optional: skill that must be learned before this skill can be learned
 */
export interface SkillLearningRequirement {
    level: number;
    statRequirementType?: SkillsStatType;
    statRequirementValue?: number;
    prerequisiteSkill?: string;
}

/**
 * Combat effect payload applied by a skill. Routes through
 * `resolveEffectApplication` (Spec 03) so resist / repel / crit follow the
 * same rules as proc-applied effects.
 *
 * @property effectId    - ID of the effect in the global effects library.
 * @property appliedTo   - 'self' or 'opponent' (relative to the caster).
 * @property description - Display text for the CLI / UI.
 */
export interface SkillCombatEffects {
    effectId: string;
    appliedTo: 'self' | 'opponent';
    description?: string;
}

/**
 * Skill entity — an ability that can be learned, equipped, and used in combat.
 *
 * @property id              - Unique identifier for this skill.
 * @property name            - Display name.
 * @property description     - Flavor text or lore.
 * @property category        - Fallacy or paradox (drives the philosophical
 *                             token generated on use).
 * @property philosophicalAspect - Stat alignment of the skill (heart/body/mind).
 * @property tier            - 1 / 2 / 3, mirrors the effect tier system.
 * @property resourceCost    - Tokens required (and spent) to use the skill.
 * @property targetType      - 'self' or 'enemy'.
 * @property basePower       - Flat damage / heal magnitude before stat scaling.
 * @property scalingStat     - Base stat the skill scales off of (typically
 *                             matches `philosophicalAspect`, but may deviate).
 * @property combatEffects   - Optional list of effect payloads to apply.
 * @property learningRequirement - Optional prerequisites needed to learn.
 */
export interface Skill {
    id: string;
    name: string;
    category: SkillCategory;
    philosophicalAspect: SkillsStatType;
    description: string;
    tier: SkillTier;
    resourceCost: ResourceCost;
    targetType: SkillTarget;
    basePower: number;
    scalingStat: SkillsStatType;
    combatEffects?: SkillCombatEffects[];
    learningRequirement?: SkillLearningRequirement;
}
