/**
 * Skills System Types
 * Skills come in two categories: fallacies and paradoxes, and run on a five-
 * resource resonance economy (heart / body / mind / fallacy / paradox). See
 * `specs/04-skills-engine.md` for the full economy design.
 */

import type { AlignmentGate } from '../NPCs/types';

/**
 * Philosophical aspect alignment for skills
 * Determines which base stat the skill scales with and which combat type it uses.
 * - 'body': Physical/strength-based skills
 * - 'mind': Mental/intelligence-based skills
 * - 'heart': Emotional/charisma-based skills
 */
export type SkillsStatType = 'body' | 'mind' | 'heart';

/**
 * Skill category type
 * - 'fallacy': Skills based on logical fallacies (generate ⚖ on use)
 * - 'paradox': Skills based on philosophical paradoxes (generate ∞ on use)
 */
export type SkillCategory = 'fallacy' | 'paradox';

/**
 * Tier of a skill — mirrors the effect tier system. Drives the resist tier
 * used when a skill applies a `combatEffects` payload through the Spec 03
 * machinery (Tier 1 auto-applies, Tier 2 resisted, Tier 3 only nat-20 repels).
 */
export type SkillTier = 1 | 2 | 3;

/**
 * Targeting scope for a skill effect.
 * - `'self'`  — the caster.
 * - `'enemy'` — the current opponent.
 * Multi-combatant targeting is deferred to Spec 07.
 */
export type SkillTarget = 'self' | 'enemy';

/**
 * Resource cost paid to use a skill. Each key maps to a `combatResources`
 * counter. Multi-key costs implicitly require resonance — the caster must
 * hold ≥ the listed amount of each resource simultaneously, and spending
 * the tokens dissolves the resonance state.
 */
export interface ResourceCost {
    heart?: number;
    body?: number;
    mind?: number;
    fallacy?: number;
    paradox?: number;
}

/**
 * Per-combat player resource counters live on `CombatState`. Seeded at combat
 * start from item/set grants, generated by player basic actions (heart/body/mind
 * from stance attacks/defends), and by player skill use (fallacy/paradox from
 * skill category/tier). Character carries `knownSkills`; current main still
 * has a legacy `equippedSkills` loadout gate scheduled for removal in Phase 99.
 * Neither field is a persistent mana/resource pool.
 */
export interface CombatResources {
    heart: number;
    body: number;
    mind: number;
    fallacy: number;
    paradox: number;
}

/**
 * Learning requirement for a skill
 * Defines the prerequisites a character must meet to learn this skill.
 * Moral-alignment gates (Spec 10) are deferred.
 *
 * @property level - Minimum character level required to learn this skill
 * @property statRequirementType - Optional: which base stat must meet the requirement (body/mind/heart)
 * @property statRequirementValue - Optional: minimum value for the specified stat
 * @property prerequisiteSkill - Optional: skill that must be learned before this skill can be learned
 */
export interface SkillLearningRequirement {
    level: number;
    statRequirementType?: SkillsStatType;
    statRequirementValue?: number;
    prerequisiteSkill?: string;
    /**
     * Phase 46 — alignment gate. Locks the skill behind a position on the
     * Phase 42 alignment cube. Single-clause gate (axis + op + value);
     * missing alignment on the character implicitly fails the gate.
     */
    requiresAlignment?: AlignmentGate;
}

/**
 * Combat effect payload applied by a skill. Routes through
 * `resolveEffectApplication` (Spec 03) so resist / repel / crit follow the
 * same rules as proc-applied effects.
 *
 * @property effectId    - ID of the effect in the global effects library.
 * @property appliedTo   - 'self' or 'opponent' (relative to the caster).
 * @property description - Display text for the CLI / UI.
 * @property intensity   - Optional initial intensity override (default 1).
 *                         Used by skills like Liar's Echo that stack a Tier 1
 *                         mark with extra intensity on first application.
 * @property duration    - Optional remaining-duration override (defaults to
 *                         the effect's library duration). Switches the apply
 *                         path into `additive` duration mode so the override
 *                         survives stacking.
 */
export interface SkillCombatEffects {
    effectId: string;
    appliedTo: 'self' | 'opponent';
    description?: string;
    intensity?: number;
    duration?: number;
}

/**
 * Bespoke skill mechanics that don't map cleanly onto an ActiveEffect
 * payload. Each is processed by `executeSkill` after damage and after
 * `combatEffects`. Kept as a discriminated union so the resolver / UI can
 * branch on `kind` without runtime tag parsing.
 *
 * - `strip_random_buff`: remove one random buff from the target. Used by
 *   Ad Hominem Strike (enemy) and similar harassment effects.
 * - `convert_enemy_buff_to_self`: strip a random buff from the enemy and
 *   apply the same effect to the player. Ship of Theseus.
 * - `secondary_heal_self`: heal the player for
 *   `baseStats[stat] × SKILL_STAT_MULTIPLIER × (multiplier ?? 1)` after the
 *   primary damage resolves. Used by Mob Appeal to bolt a small self-heal
 *   onto an enemy-targeted strike.
 * - `bypass_defense`: marker flag indicating the skill ignores defence math.
 *   `calculateSkillDamage` already produces flat damage today, so this is a
 *   no-op marker; it is preserved so future damage paths can branch on it
 *   without changing the library.
 * - `befriend_attempt`: Phase 108 - attempt to befriend the enemy, opening
 *   a mercy choice state if successful (requires HP gate eligibility).
 */
export type SkillSpecialMechanic =
    | { kind: 'strip_random_buff'; appliedTo: 'self' | 'enemy' }
    | { kind: 'convert_enemy_buff_to_self' }
    | { kind: 'secondary_heal_self'; stat: SkillsStatType; multiplier?: number }
    | { kind: 'bypass_defense' }
    | { kind: 'befriend_attempt' };

/**
 * Phase 66 — synergy predicate. The matched ActiveEffect on `on`
 * satisfies the predicate when its `effectId` matches AND its
 * `intensity` >= `intensityMin` (if set) AND its `remainingDuration`
 * >= `durationMin` (if set).
 */
export interface SynergyPredicate {
    effectId: string;
    on: 'caster' | 'target';
    intensityMin?: number;
    durationMin?: number;
}

/**
 * Phase 66 — Tier 2 synergy clause. Optional payload on `Skill` that
 * rewards stance-switching by conditioning damage / effect application
 * on the presence of an ActiveEffect already on the field (or, for
 * Resonance Detonation, on the unconditional cast).
 *
 * Synergy damage (added to the skill's base damage; doesn't replace):
 * ```
 * synergyDamage = bonusDamage
 *               + matched.intensity            × intensityDamageMul
 *               + matched.remainingDuration    × durationDamageMul
 *               + consumedTokens               × resourceTokenDamageMul
 * ```
 *
 * Side effects (in resolution order):
 *   1. `consumeAllResources` zeros the caster's `combatResources` pool
 *      and captures `consumedTokens = body + mind + heart` for the
 *      damage formula.
 *   2. Synergy damage applies to the target.
 *   3. `consumeMatched` clears the matched ActiveEffect on the
 *      predicate's `on` side.
 *   4. `clearAllEffectsBothSides` clears all ActiveEffects on both
 *      combatants (Phase 60 set-bonus passives included — design
 *      intent per Phase 66 D9).
 *   5. `applyEffectOnFire` applies a fresh effect (typically used to
 *      "swap type" — body Thorns → heart Bat-Swarm-Thoughtform).
 *
 * Synergy runs in `executeSkill` AFTER `calculateSkillDamage` but
 * BEFORE the skill's own `combatEffects` apply, so consumed effects
 * don't get post-fire effects layered on top.
 */
export interface SkillSynergy {
    /** Optional predicate. If absent, the synergy fires unconditionally
     *  when the skill is cast (used by Resonance Detonation per D6). */
    predicate?: SynergyPredicate;
    /** Flat bonus damage on match. */
    bonusDamage?: number;
    /** Multiplier × matched effect's `remainingDuration`. */
    durationDamageMul?: number;
    /** Multiplier × matched effect's `intensity`. */
    intensityDamageMul?: number;
    /** Multiplier × total consumed combat-resource tokens (only fires
     *  when `consumeAllResources` is true). */
    resourceTokenDamageMul?: number;
    /** Clear the matched effect from the predicate's `on` side. */
    consumeMatched?: boolean;
    /** Zero the caster's full `combatResources` pool. */
    consumeAllResources?: boolean;
    /** Clear all ActiveEffects from both combatants. */
    clearAllEffectsBothSides?: boolean;
    /** Apply an additional effect on the caster when synergy fires. */
    applyEffectOnFire?: SkillCombatEffects;
}

/**
 * Skill entity — an ability that can be learned/unlocked and used in combat.
 *
 * @property id              - Unique identifier for this skill.
 * @property name            - Display name.
 * @property description     - Flavor text or lore.
 * @property category        - Fallacy or paradox (drives the philosophical
 *                             token generated on use).
 * @property philosophicalAspect - Stat alignment of the skill (heart/body/mind).
 * @property tier            - 1 / 2 / 3, mirrors the effect tier system.
 * @property resourceCost    - Tokens required (and spent) to use the skill.
 * @property targetType      - 'self' or 'enemy'.
 * @property basePower       - Flat damage / heal magnitude before stat scaling.
 * @property scalingStat     - Base stat the skill scales off of (typically
 *                             matches `philosophicalAspect`, but may deviate).
 * @property scalingMultiplier - Optional multiplier on the scaling-stat term
 *                               (default 1). Skill damage / heal becomes
 *                               `basePower + stat × SKILL_STAT_MULTIPLIER × scalingMultiplier`.
 *                               Used by self-heals like Appeal to Pity that want
 *                               a more substantial restorative effect.
 * @property combatEffects   - Optional list of effect payloads to apply.
 * @property specialMechanics - Optional bespoke behaviours (buff-strip,
 *                              buff-conversion, secondary heal, etc.). Resolved
 *                              after damage and after `combatEffects`.
 * @property learningRequirement - Optional prerequisites needed to learn.
 */
export interface Skill {
    id: string;
    name: string;
    category: SkillCategory;
    philosophicalAspect: SkillsStatType;
    description: string;
    tier: SkillTier;
    resourceCost: ResourceCost;
    targetType: SkillTarget;
    basePower: number;
    scalingStat: SkillsStatType;
    scalingMultiplier?: number;
    combatEffects?: SkillCombatEffects[];
    specialMechanics?: SkillSpecialMechanic[];
    learningRequirement?: SkillLearningRequirement;
    /**
     * Phase 44 — cross-link back to the originating
     * `PhilosophicalAlignmentCell.id` (kebab-case) for skills authored
     * from a fallacy in the 27-cell library. Optional; only set on
     * philosophy-sourced skills. See `docs/philosophy.md`.
     */
    sourcedFromCell?: string;
    /**
     * Phase 66 — Tier 2 synergy clause. When present, the skill engine
     * evaluates the synergy after `calculateSkillDamage` and before
     * applying `combatEffects` / `specialMechanics`. See {@link SkillSynergy}.
     */
    synergy?: SkillSynergy;
    /**
     * Phase 91 — Optional friendship counter increment. When present, executeSkill
     * increments the combat friendship counter by this amount after damage/effects
     * but before resource costs. Does not require defend stance.
     */
    incrementsFriendship?: number;
    /**
     * Content-provenance metadata used by the tuning `--focus` filter
     * (`src/Tuning/focus.parser.ts`). `addedIn` is an ISO date / phase tag;
     * `tags` are freeform labels (e.g. `'mid-game'`, `'damage'`). Both
     * optional and ignored by the skill engine.
     */
    addedIn?: string;
    tags?: string[];
}
