/**
 * Skills System Types
 * Skills come in two categories: fallacies and paradoxes, and run on a five-
 * resource resonance economy (heart / body / mind / fallacy / paradox). See
 * `specs/04-skills-engine.md` for the full economy design.
 */

/**
 * Philosophical aspect alignment for skills
 * Determines which base stat the skill scales with and which combat type it uses.
 * - 'body': Physical/strength-based skills
 * - 'mind': Mental/intelligence-based skills
 * - 'heart': Emotional/charisma-based skills
 */
export type SkillsStatType = 'body' | 'mind' | 'heart';

/**
 * Skill category type
 * - 'fallacy': Skills based on logical fallacies (generate ⚖ on use)
 * - 'paradox': Skills based on philosophical paradoxes (generate ∞ on use)
 */
export type SkillCategory = 'fallacy' | 'paradox';

/**
 * Tier of a skill — mirrors the effect tier system. Drives the resist tier
 * used when a skill applies a `combatEffects` payload through the Spec 03
 * machinery (Tier 1 auto-applies, Tier 2 resisted, Tier 3 only nat-20 repels).
 */
export type SkillTier = 1 | 2 | 3;

/**
 * Targeting scope for a skill effect.
 * - `'self'`  — the caster.
 * - `'enemy'` — the current opponent.
 * Multi-combatant targeting is deferred to Spec 07.
 */
export type SkillTarget = 'self' | 'enemy';

/**
 * Resource cost paid to use a skill. Each key maps to a `combatResources`
 * counter. Multi-key costs implicitly require resonance — the caster must
 * hold ≥ the listed amount of each resource simultaneously, and spending
 * the tokens dissolves the resonance state.
 */
export interface ResourceCost {
    heart?: number;
    body?: number;
    mind?: number;
    fallacy?: number;
    paradox?: number;
}

/**
 * Per-combat resource counters lived on `CombatState`. Generated by basic
 * actions (heart/body/mind from stance attacks/defends) and by skill use
 * (fallacy/paradox from skill category).
 */
export interface CombatResources {
    heart: number;
    body: number;
    mind: number;
    fallacy: number;
    paradox: number;
}

/**
 * Learning requirement for a skill
 * Defines the prerequisites a character must meet to learn this skill.
 * Moral-alignment gates (Spec 10) are deferred.
 *
 * @property level - Minimum character level required to learn this skill
 * @property statRequirementType - Optional: which base stat must meet the requirement (body/mind/heart)
 * @property statRequirementValue - Optional: minimum value for the specified stat
 * @property prerequisiteSkill - Optional: skill that must be learned before this skill can be learned
 */
export interface SkillLearningRequirement {
    level: number;
    statRequirementType?: SkillsStatType;
    statRequirementValue?: number;
    prerequisiteSkill?: string;
}

/**
 * Combat effect payload applied by a skill. Routes through
 * `resolveEffectApplication` (Spec 03) so resist / repel / crit follow the
 * same rules as proc-applied effects.
 *
 * @property effectId    - ID of the effect in the global effects library.
 * @property appliedTo   - 'self' or 'opponent' (relative to the caster).
 * @property description - Display text for the CLI / UI.
 * @property intensity   - Optional initial intensity override (default 1).
 *                         Used by skills like Liar's Echo that stack a Tier 1
 *                         mark with extra intensity on first application.
 * @property duration    - Optional remaining-duration override (defaults to
 *                         the effect's library duration). Switches the apply
 *                         path into `additive` duration mode so the override
 *                         survives stacking.
 */
export interface SkillCombatEffects {
    effectId: string;
    appliedTo: 'self' | 'opponent';
    description?: string;
    intensity?: number;
    duration?: number;
}

/**
 * Bespoke skill mechanics that don't map cleanly onto an ActiveEffect
 * payload. Each is processed by `executeSkill` after damage and after
 * `combatEffects`. Kept as a discriminated union so the resolver / UI can
 * branch on `kind` without runtime tag parsing.
 *
 * - `strip_random_buff`: remove one random buff from the target. Used by
 *   Ad Hominem Strike (enemy) and similar harassment effects.
 * - `convert_enemy_buff_to_self`: strip a random buff from the enemy and
 *   apply the same effect to the player. Ship of Theseus.
 * - `secondary_heal_self`: heal the player for
 *   `baseStats[stat] × SKILL_STAT_MULTIPLIER × (multiplier ?? 1)` after the
 *   primary damage resolves. Used by Mob Appeal to bolt a small self-heal
 *   onto an enemy-targeted strike.
 * - `bypass_defense`: marker flag indicating the skill ignores defence math.
 *   `calculateSkillDamage` already produces flat damage today, so this is a
 *   no-op marker; it is preserved so future damage paths can branch on it
 *   without changing the library.
 */
export type SkillSpecialMechanic =
    | { kind: 'strip_random_buff'; appliedTo: 'self' | 'enemy' }
    | { kind: 'convert_enemy_buff_to_self' }
    | { kind: 'secondary_heal_self'; stat: SkillsStatType; multiplier?: number }
    | { kind: 'bypass_defense' };

/**
 * Skill entity — an ability that can be learned, equipped, and used in combat.
 *
 * @property id              - Unique identifier for this skill.
 * @property name            - Display name.
 * @property description     - Flavor text or lore.
 * @property category        - Fallacy or paradox (drives the philosophical
 *                             token generated on use).
 * @property philosophicalAspect - Stat alignment of the skill (heart/body/mind).
 * @property tier            - 1 / 2 / 3, mirrors the effect tier system.
 * @property resourceCost    - Tokens required (and spent) to use the skill.
 * @property targetType      - 'self' or 'enemy'.
 * @property basePower       - Flat damage / heal magnitude before stat scaling.
 * @property scalingStat     - Base stat the skill scales off of (typically
 *                             matches `philosophicalAspect`, but may deviate).
 * @property scalingMultiplier - Optional multiplier on the scaling-stat term
 *                               (default 1). Skill damage / heal becomes
 *                               `basePower + stat × SKILL_STAT_MULTIPLIER × scalingMultiplier`.
 *                               Used by self-heals like Appeal to Pity that want
 *                               a more substantial restorative effect.
 * @property combatEffects   - Optional list of effect payloads to apply.
 * @property specialMechanics - Optional bespoke behaviours (buff-strip,
 *                              buff-conversion, secondary heal, etc.). Resolved
 *                              after damage and after `combatEffects`.
 * @property learningRequirement - Optional prerequisites needed to learn.
 */
export interface Skill {
    id: string;
    name: string;
    category: SkillCategory;
    philosophicalAspect: SkillsStatType;
    description: string;
    tier: SkillTier;
    resourceCost: ResourceCost;
    targetType: SkillTarget;
    basePower: number;
    scalingStat: SkillsStatType;
    scalingMultiplier?: number;
    combatEffects?: SkillCombatEffects[];
    specialMechanics?: SkillSpecialMechanic[];
    learningRequirement?: SkillLearningRequirement;
    /**
     * Phase 44 — cross-link back to the originating
     * `PhilosophicalAlignmentCell.id` (kebab-case) for skills authored
     * from a fallacy in the 27-cell library. Optional; only set on
     * philosophy-sourced skills. See `docs/philosophy.md`.
     */
    sourcedFromCell?: string;
}
